### ISSUE TITLE
a fatal error when none tag image

### ISSUE THREAD

**Issue by ziserendexin** [pyouroboros/ouroboros#122]
Error：
```
Traceback (most recent call last):
  File "pyouroboros/ouroboros.py", line 184, in <module>
    main()
  File "pyouroboros/ouroboros.py", line 169, in main
    docker = Docker(socket, config, data_manager, notification_manager)
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 17, in __init__
    self.monitored = self.monitor_filter()
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 42, in monitor_filter
    running_containers = self.get_running()
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 31, in get_running
    if 'ouroboros' not in container.image.tags[0]:
IndexError: list index out of range

```

Preliminary positioning:
I have many images. like:
```
[root@ ~]# docker images
REPOSITORY                         TAG                  IMAGE ID            CREATED             SIZE
this_ouroboros                     lastest              1a165e430370        2 hours ago         92.5MB
this_ouroboros                     latest               1a165e430370        2 hours ago         92.5MB
pyouroboros/ouroboros              latest               635243d2fb67        26 hours ago        101MB
amd64/python                       3.7.2-alpine         1a8edcb29ce4        3 weeks ago         78.5MB
mabo/chitu                         170728-0.1.5         e79fdc6e5c55        5 weeks ago         169MB
mabo/chitu                         180906-0.1.5         ee6c5be5bde4        5 weeks ago         169MB
mabo/chitu                         latest               ee6c5be5bde4        5 weeks ago         169MB
mabo/python                        3.7.1-alpine-0.1.5   6ffa7397a2d4        5 weeks ago         169MB
mabo/python                        latest               6ffa7397a2d4        5 weeks ago         169MB
mabo/chitu                         170728-0.1.4         f33e80d4c4fa        2 months ago        149MB
mabo/chitu                         180906-0.1.4         19f8872c5a45        2 months ago        149MB
mabo/python                        3.7.1-alpine-0.1.4   eacfcd93f032        2 months ago        149MB
python                             3.7.1-alpine         408808fb1a9e        2 months ago        78.2MB
mysql                              latest               2dd01afbe8df        2 months ago        485MB
redis                              latest               1babb1dde7e1        3 months ago        94.9MB
influxdb                           latest               396b2bd13e14        3 months ago        213MB
grafana/grafana                    latest               7038dbc9a50c        3 months ago        223MB
kapacitor                          latest               8d8970dc76ce        3 months ago        254MB
telegraf                           latest               5bb3171720ed        3 months ago        230MB
nginx                              latest               dbfc48660aeb        3 months ago        109MB
chronograf                         latest               8a9adbf901e4        3 months ago        153MB
centos                             latest               75835a67d134        3 months ago        200MB
mabo/chitu                         180906-0.1.3         19fb6a0b26c5        3 months ago        147MB
mabo/python                        3.7.0-alpine-0.1.3   1341d8248b89        3 months ago        147MB
python                             3.7.0-alpine         d30308ec4dc1        4 months ago        78.1MB
redis                              <none>               e1a73233e3be        4 months ago        83.4MB
mabo/python                        3.7.0-alpine-0.1.2   85dc1764c778        4 months ago        149MB
mabo/chitu                         170728-0.1.1         199ad01f76c7        4 months ago        149MB
mabo/python                        3.7.0-alpine-0.1.1   d3bd5eeb2c3d        4 months ago        149MB
python                             <none>               a5f497d596f5        5 months ago        79.4MB
python                             3.7.0-stretch        825141134528        5 months ago        923MB
portainer/portainer                latest               6827bc26a94d        5 months ago        58.5MB
<none>                             <none>               f06a5773f01e        6 months ago        83.4MB
alpine                             3.7                  791c3e2ebfcb        6 months ago        4.2MB
v2tec/watchtower                   latest               3069a9fb302a        10 months ago       9.49MB
adiazmor/docker-ubuntu-with-ping   latest               add88055ea03        2 years ago         173MB

```
noticed there have some images with \<none\> TAG.
and running container:
```
docker ps -a
CONTAINER ID        IMAGE                 COMMAND                  CREATED             STATUS                         PORTS                      NAMES
727d885034b7        this_ouroboros        "tail -f /app/requir…"   24 minutes ago      Up 24 minutes                                             ouroboros
4cfc9cbfb5eb        93f2b0517e9e          "/bin/sh -c 'apk add…"   About an hour ago   Exited (1) About an hour ago                              compassionate_booth
a44cb14201e2        a1aeb4fb6a46          "/bin/sh -c 'apk add…"   About an hour ago   Exited (1) About an hour ago                              kind_boyd
88dc77c867ed        mabo/python           "python /usr/mabo/zi…"   2 weeks ago         Up 11 days                     0.0.0.0:31500->31500/tcp   doctopus-tcp-mts_ziyan_tcp_mts_1
6d3d40c04281        redis:latest          "docker-entrypoint.s…"   2 weeks ago         Up 11 days                     6379/tcp                   doctopus-tcp-mts_redis_1
eb5dbf97bb65        portainer/portainer   "/portainer -H unix:…"   3 weeks ago         Up 11 days                     0.0.0.0:9000->9000/tcp     portainer_portainer_1
be8bb52a3123        influxdb              "/entrypoint.sh infl…"   2 months ago        Up 11 days                     8086/tcp                   influxdb_all_nginx_influxdb_1
0b08e16e580b        f06a5773f01e          "docker-entrypoint.s…"   4 months ago        Up 11 days                     0.0.0.0:6379->6379/tcp     redis


```

and add info in /pyouroboros/dockerclient.py
```
            for container in self.client.containers.list(filters={'status': 'running'}):
                self.logger.info(f"container.image.tags:{container.image.tags}")      # <==== here
                if self.config.self_update:
                    running_containers.append(container)
                else:
                    if 'ouroboros' not in container.image.tags[0]:
                        running_containers.append(container)
```

get log:
```
python pyouroboros/ouroboros.py
2019-01-18 06:22:05 : INFO : ouroboros : Version: 0.6.0-master
2019-01-18 06:22:05 : INFO : dockerclient : here
2019-01-18 06:22:05 : INFO : dockerclient : container.image.tags:['this_ouroboros:lastest', 'this_ouroboros:latest']
2019-01-18 06:22:05 : INFO : dockerclient : container.image.tags:['mabo/python:3.7.1-alpine-0.1.5', 'mabo/python:latest']
2019-01-18 06:22:05 : INFO : dockerclient : container.image.tags:['redis:latest']
2019-01-18 06:22:05 : INFO : dockerclient : container.image.tags:['portainer/portainer:latest']
2019-01-18 06:22:05 : INFO : dockerclient : container.image.tags:['influxdb:latest']
2019-01-18 06:22:06 : INFO : dockerclient : container.image.tags:[]
Traceback (most recent call last):
  File "pyouroboros/ouroboros.py", line 184, in <module>
    main()
  File "pyouroboros/ouroboros.py", line 169, in main
    docker = Docker(socket, config, data_manager, notification_manager)
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 17, in __init__
    self.monitored = self.monitor_filter()
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 42, in monitor_filter
    running_containers = self.get_running()
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 31, in get_running
    if 'ouroboros' not in container.image.tags[0]:
IndexError: list index out of range
```

so there have a [] in container.image.tags~

in this case, should deal it.   : D

**Comment by DirtyCajunRice** [comment]
@ziserendexin this is fixed in develop!
