### ISSUE TITLE
Unexpected docker API causes program to quit ‘500 Server Error: Internal Server Error’

### ISSUE THREAD

**Issue by ziserendexin** [pyouroboros/ouroboros#130]
The log of ouroboros:
```
ouroboros    | 2019-01-22 10:22:24 : DEBUG : dockerclient : Pulling tag: pyouroboros/ouroboros:latest
ouroboros    | 2019-01-22 10:22:24 : DEBUG : auth : Looking for auth config
ouroboros    | 2019-01-22 10:22:24 : DEBUG : auth : No auth config in memory - loading from filesystem
ouroboros    | 2019-01-22 10:22:24 : DEBUG : config : Trying paths: ['/********root/.docker/config.json', '/********root/.dockercfg']
ouroboros    | 2019-01-22 10:22:24 : DEBUG : config : No config file found
ouroboros    | 2019-01-22 10:22:24 : DEBUG : auth : Looking for auth entry for 'docker.io'
ouroboros    | 2019-01-22 10:22:24 : DEBUG : auth : No entry found
ouroboros    | 2019-01-22 10:22:24 : DEBUG : auth : No auth config found
ouroboros    | 2019-01-22 10:22:57 : DEBUG : connectionpool : http://localhost:None "POST /v1.35/images/create?tag=latest&fromImage=pyouroboros%2Fouroboros HTTP/1.1" 500 233
ouroboros    | 2019-01-22 10:22:57 : CRITICAL : dockerclient : 500 Server Error: Internal Server Error ("Get https://registry-1.docker.io/v2/pyouroboros/ouroboros/manifests/latest: Get https://auth.docker.io/token?scope=repository%3Apyouroboros%2Fouroboros%3Apull&service=registry.docker.io: net/http: TLS handshake timeout")
ouroboros    | Traceback (most recent call last):
ouroboros    |   File "/usr/local/bin/ouroboros", line 5, in <module>
ouroboros    |     main()
ouroboros    |   File "/usr/local/lib/python3.7/site-packages/pyouroboros/ouroboros.py", line 179, in main
ouroboros    |     schedule.run_pending()
ouroboros    |   File "/usr/local/lib/python3.7/site-packages/schedule/__init__.py", line 493, in run_pending
ouroboros    |     default_scheduler.run_pending()
ouroboros    |   File "/usr/local/lib/python3.7/site-packages/schedule/__init__.py", line 78, in run_pending
ouroboros    |     self._run_job(job)
ouroboros    |   File "/usr/local/lib/python3.7/site-packages/schedule/__init__.py", line 131, in _run_job
ouroboros    |     ret = job.run()
ouroboros    |   File "/usr/local/lib/python3.7/site-packages/schedule/__init__.py", line 411, in run
ouroboros    |     ret = self.job_func()
ouroboros    |   File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 116, in update_containers
ouroboros    |     if current_image.id != latest_image.id:
ouroboros    | AttributeError: 'NoneType' object has no attribute 'id'
ouroboros exited with code 1
```

And an test in python : 
```
[root@ docker_image]# docker exec -it test python
Python 3.7.2 (default, Dec 26 2018, 08:50:25) 
[GCC 6.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from docker import DockerClient

>>> client = DockerClient(base_url='unix://var/run/docker.sock')
>>> client.images.pull('pyouroboros/ouroboros:latest')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 256, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.35/images/create?tag=latest&fromImage=pyouroboros%2Fouroboros

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/docker/models/images.py", line 441, in pull
    repository, tag=tag, stream=True, **kwargs
  File "/usr/local/lib/python3.7/site-packages/docker/api/image.py", line 400, in pull
    self._raise_for_status(response)
  File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 258, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python3.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("Get https://registry-1.docker.io/v2/: EOF")
```
In my check, its because my company network user authentication is time out...Orz...

Reset network,it`s ok.

Is it better to catch this APIError?
https://github.com/pyouroboros/ouroboros/blob/b14186a5c45fc496d4fe7218aacd2e28700eac59/pyouroboros/dockerclient.py#L75

**Comment by circa10a** [comment]
are you running this via cli? or in a container using `--self-update`?

**Comment by ziserendexin** [comment]
> are you running this via cli? or in a container using `--self-update`?

yes~

**Comment by circa10a** [comment]
> > are you running this via cli? or in a container using `--self-update`?
> 
> yes~

Could you clarify which is it?

**Comment by ziserendexin** [comment]
> > > are you running this via cli? or in a container using `--self-update`?
> > 
> > 
> > yes~
> 
> Could you clarify which is it?

my command is 
command: "--interval 60 --log-level debug --latest --self-update" 

but it not because self update or pull. it's ignore a possible but not interrupted error.

and i think # 130 is enough.
https://github.com/pyouroboros/ouroboros/commit/bb0f1d184d132da14846143c8a100c6ff16ec580

**Comment by circa10a** [comment]
@DirtyCajunRice is quick

![alt text](https://m.media-amazon.com/images/M/MV5BNjRlYjgwMWMtNDFmMy00OWQ0LWFhMTMtNWE3MTU4ZjQ3MjgyXkEyXkFqcGdeQXVyNzU1NzE3NTg@._V1_CR0,45,480,270_AL_UX477_CR0,0,477,268_AL_.jpg)

**Comment by DirtyCajunRice** [comment]
fixed in develop
