### ISSUE TITLE
Ouroboros Container stopping.

### ISSUE THREAD

**Issue by P3nkiln** [pyouroboros/ouroboros#176]
I'm currently having an issue. I installed Ouroboros a few days ago and it worked fine. I just looked on Portainer and noticed it was stopped and there were 2 Ouroboros containers, neither of which were running. Restarting either of the containers immediately stops. I deleted both containers and images and clean installed to still have the same issue. 

docker logs ouroboros:

2019-02-02 13:48:19 : INFO : ouroboros : Version: 1.1.1-master
2019-02-02 13:48:19 : INFO : base : Scheduler started
Traceback (most recent call last):
  File "/usr/local/bin/ouroboros", line 5, in <module>
    main()
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/ouroboros.py", line 171, in main
    name=f'Initial run interval container update for {socket}'
  File "/usr/local/lib/python3.7/site-packages/apscheduler/schedulers/base.py", line 416, in add_job
    'trigger': self._create_trigger(trigger, trigger_args),
  File "/usr/local/lib/python3.7/site-packages/apscheduler/schedulers/base.py", line 918, in _create_trigger
    return self._create_plugin_instance('trigger', trigger, trigger_args)
  File "/usr/local/lib/python3.7/site-packages/apscheduler/schedulers/base.py", line 903, in _create_plugin_instance
    return plugin_cls(**constructor_kwargs)
  File "/usr/local/lib/python3.7/site-packages/apscheduler/triggers/date.py", line 20, in __init__
    timezone = astimezone(timezone) or get_localzone()
  File "/usr/local/lib/python3.7/site-packages/apscheduler/util.py", line 87, in astimezone
    'Unable to determine the name of the local timezone -- you must explicitly '
ValueError: Unable to determine the name of the local timezone -- you must explicitly specify the name of the local timezone. Please refrain from using timezones like EST to prevent problems with daylight saving time. Instead, use a locale based timezone name (such as Europe/Helsinki).

Any help would be greatly appreciated.

**Comment by tlkamp** [comment]
Thanks for opening an issue!

This error seems to be related to the time one you're specifying. Can you share your config (minus any sensitive bits)?

**Comment by P3nkiln** [comment]
It's a ubuntu 18.04 vps located in the Czech Republic. Latest version of Docker.

If you'd like a more detailed config, what would be the best way?

**Comment by cdelalama** [comment]
Same issue here. Solved it adding my time zone in the configuration (in my case Madrid):
-e TZ=Europe/Madrid
Without it, I get the same error than P3nkiln

**Comment by tlkamp** [comment]
Seems like this is a bug for ouroboros when no TZ is set. Thank you for reporting!

**Comment by tlkamp** [comment]
@P3nkiln Please try adding `-e TZ=Europe/Prague` to your config until we push a fix.

**Comment by P3nkiln** [comment]
@tlkamp Sorry I couldn't reply with more information quicker. Setting the TZ with that variable works a treat. Thanks for the quick replies and fix.
