### ISSUE TITLE
Exception when updating container started with --rm (autoremove) 

### ISSUE THREAD

**Issue by nightvisi0n** [pyouroboros/ouroboros#219]
If a container is started with [`--rm`](https://docs.docker.com/engine/reference/run/#clean-up---rm) and ouroboros tries to update it, an exception is triggered:

```python
2019-02-15 12:56:18 : ERROR : base : Job "Run Once container update for unix://var/run/docker.sock (trigger: date[2019-02-15 12:56:03 UTC], next run at: 2019-02-15 12:56:03 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 256, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http+docker://localhost/v1.35/containers/2e566328adc76054a2bfc2a7ebffdb118dbbed3133cd637bb25bb21c0befcee9?v=False&link=False&force=False

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 301, in update
    self.recreate(container, latest_image)
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 97, in recreate
    self.remove(container)
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 88, in remove
    container.remove()
  File "/usr/local/lib/python3.7/site-packages/docker/models/containers.py", line 339, in remove
    return self.client.api.remove_container(self.id, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/docker/api/container.py", line 992, in remove_container
    self._raise_for_status(res)
  File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 258, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python3.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 409 Client Error: Conflict ("removal of container 2e566328adc76054a2bfc2a7ebffdb118dbbed3133cd637bb25bb21c0befcee9 is already in progress")
```

Execute the following in order to reproduce the issue:  

```
docker pull fedora:28
docker tag fedora:28 fedora:latest
docker run -d --rm --name=test fedora:latest sleep 999999
docker run -it --rm --name=ouroboros --hostname=ouroboros -v /var/run/docker.sock:/var/run/docker.sock ouroboros --run-once
```

**Comment by circa10a** [comment]
We'll need to do an initial check for:

```python
>>> client.containers.get('nginx').attrs['HostConfig']['AutoRemove']
True
```

Perhaps best place for this is to do a check and if `true` not append to `running_containers` in `dockerclient.running_filter()`. Thoughts @DirtyCajunRice ?

**Comment by DirtyCajunRice** [comment]
yep. that simple. that is golden

**Comment by circa10a** [comment]
fixed in develop

**Comment by celvin** [comment]
Edit the Dockerfile (add one string, `sed -i "s/999/99/" /etc/group`) fixed it to me:
In alpine

FROM library/docker:stable

ENV HOME_DIR=/opt/crontab
RUN apk add --no-cache --virtual .run-deps bash jq \
    && mkdir -p ${HOME_DIR}/jobs ${HOME_DIR}/projects \
    && adduser -S docker -D \
    && sed -i "s/999/99/" /etc/group

**Comment by keppo070** [comment]
I have this issue also. It seems to be closed, but i have this happen just now. I'm running the latest version.

2019-06-30 07:19:50 : INFO : ouroboros : Version: 1.4.1-master
2019-06-30 07:19:51 : INFO : NotifyTelegram : Sent Telegram notification.
2019-06-30 07:21:27 : INFO : dockerclient : sabnzbd will be updated
2019-06-30 07:21:40 : ERROR : base : Job "Initial run interval container update for unix://var/run/docker                   .sock (trigger: date[2019-06-30 07:19:50 UTC], next run at: 2019-06-30 07:19:50 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http+docker://localhost/v1.35/containe                   rs/36304057d760db270dc5aecd9fd4e398c6f79fa6fc77b09af1ce35db9e9e300c?v=False&link=False&force=False
