### ISSUE TITLE
Exception when restarting updated container

### ISSUE THREAD

**Issue by yildiz-online** [pyouroboros/ouroboros#225]
Hello, i receive an exception when starting the container after an update from ouroboros, keeping it stuck at 'started' state, requiring a compose up to make it running:

```
2019-02-17 18:00:32 : ERROR : base : Job "Interval container update for unix://var/run/docker.sock (trigger: interval[0:05:00], next run at: 2019-02-17 18:05:10 CET)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 301, in update
    self.recreate(container, latest_image)
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 117, in recreate
    network.connect(**new_network_config)
  File "/usr/local/lib/python3.7/site-packages/docker/models/networks.py", line 57, in connect
    container, self.id, *args, **kwargs
  File "/usr/local/lib/python3.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/docker/api/network.py", line 242, in connect_container_to_network
    ipv6_address=ipv6_address, link_local_ips=link_local_ips
  File "/usr/local/lib/python3.7/site-packages/docker/api/container.py", line 649, in create_endpoint_config
    return EndpointConfig(self._version, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/docker/types/networks.py", line 17, in __init__
    self["Links"] = normalize_links(links)
  File "/usr/local/lib/python3.7/site-packages/docker/utils/utils.py", line 447, in normalize_links
    return ['{0}:{1}'.format(k, v) if v else k for k, v in sorted(links)]
  File "/usr/local/lib/python3.7/site-packages/docker/utils/utils.py", line 447, in <listcomp>
    return ['{0}:{1}'.format(k, v) if v else k for k, v in sorted(links)]
ValueError: too many values to unpack (expected 2)`
```
Docker-compose configuration:  
```yaml
game-server:
    container_name: yildiz-game-server
    image: moussavdb/application-yildiz_online:latest
    restart: always
    environment:
      - TZ=Europe/Brussels
    ports:
      - 10701:10701
    links:
      - "splunk:splunk"
      - "broker:broker"
    volumes:
      - ~/yildiz/config/yildiz-online:/config
    entrypoint: java -jar game-server-assembly.jar configuration=/config/config.properties`
```
My other images having no issues, i suspect the configuration=/config/config.properties not being interpreted properly.

**Comment by circa10a** [comment]
@yildiz-online What version of ouroboros do you have?(it's the first line when running with debug loglevel)

Can you also format the compose configuration in yaml?

```yaml
some:
  example: yaml
```

**Comment by yildiz-online** [comment]
2019-02-16 11:25:10 : INFO : ouroboros : Version: 1.2.1-master

```yaml
game-server: 

  container_name: yildiz-game-server
  image: moussavdb/application-yildiz_online:latest 
  restart: always 
  environment:
    - TZ=Europe/Brussels 
  ports:
    - 10701:10701
  links: 
    - "splunk:splunk" 
    - "broker:broker" 
  volumes: 
    - ~/yildiz/config/yildiz-online:/config 
  entrypoint: java -jar game-server-assembly.jar configuration=/config/config.properties

```

**Comment by circa10a** [comment]
So the container is present but ouroboros fails to start it correct? If so, what happens when you try to `docker start` it?

**Comment by yildiz-online** [comment]
Yes the container is there, in created state.

But when using docker start, or docker-compose up -d, it works properly, with the container in 'running' state.

**Comment by DirtyCajunRice** [comment]
its nothing to do with the entrypoint. the error above (i reformatted for you) shows an error during docker-py's ability to recreate the links. e.g.:
```
File "/usr/local/lib/python3.7/site-packages/docker/utils/utils.py", line 447, in <listcomp>
    return ['{0}:{1}'.format(k, v) if v else k for k, v in sorted(links)]
```

**Comment by yildiz-online** [comment]
ok, so what should i do?

**Comment by circa10a** [comment]
Can you try using a docker network instead of links?

**Comment by yildiz-online** [comment]
mmh, anyway i have to enable ipv6, so seems this will get out from the backlog earlier than expected, could take some time, i am not yet experienced with docker network, i ll notify here if the problem gets fixed

**Comment by yildiz-online** [comment]
Creating manually a network and attaching the compose services to it seems to have resolved the issues (1 container updated and restarted successfully till now)

**Comment by yildiz-online** [comment]
Hi @hannonq 

I removed all the "link" entries
You already have your network defined(internal, traefik_proxy)
