### ISSUE TITLE
Since 1.3.0, docker login fails

### ISSUE THREAD

**Issue by yildiz-online** [pyouroboros/ouroboros#243]
Since the latest update, private image can no longer be pulled, it was running fine with 1.2.x, no change on config

CRITICAL : dockerclient : Couldn't pull. Skipping. Error: 404 Client Error: Not Found ("pull access denied for moussavdb/application-yildiz_online, repository does not exist or may require 'docker login'")

**Comment by DirtyCajunRice** [comment]
Sigh. We allowed someone to make a change and didnt test it thoroughly enough. Ill fix it today and push a patch fix.

**Comment by DirtyCajunRice** [comment]
Once the above is merged in to develop can you ensure its back to working as expected?

**Comment by yildiz-online** [comment]
Sure, i'll notify you of any change

**Comment by DirtyCajunRice** [comment]
please test develop

**Comment by yildiz-online** [comment]
With develop tag: The login seems fixed (2019-02-27 21:48:33 : INFO : dockerclient : yildiz-game-server will be updated)
Anyway new exception:

2019-02-27 21:48:10 : INFO : ouroboros : Version: 1.3.0-master

2019-02-27 21:48:11 : ERROR : base : Job "Self Check for unix://var/run/docker.sock (trigger: date[2019-02-27 21:48:10 CET], next run at: 2019-02-27 21:48:10 CET)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 233, in self_check
    me_list = [c for c in self.monitored if 'ouroboros' in c['Names'][0].strip('/')]
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 233, in <listcomp>
    me_list = [c for c in self.monitored if 'ouroboros' in c['Names'][0].strip('/')]
TypeError: 'Container' object is not subscriptable
2019-02-27 21:48:33 : INFO : dockerclient : yildiz-game-server will be updated

**Comment by DirtyCajunRice** [comment]
Pushing to master
