### ISSUE TITLE
Timeout error?

### ISSUE THREAD

**Issue by imbaimbaimba** [pyouroboros/ouroboros#250]
Hi! 
I just started using Ouroboros, and it already updated a bunch of my containers. However, after updating a handful, it gave me a timeout error. I cannot read any code, so I am afraid I have no idea what is going on.

I am sorry that the log is upside down in my Synology, hope you can start from the bottom :)

```
2019-02-28 22:41:04 | stderr | 2019-02-28 23:41:04 : ERROR : base : Job "Initial run interval container update for unix://var/run/docker.sock (trigger: date[2019-02-28 23:29:58 CET], next run at: 2019-02-28 23:29:58 CET)" raised an exception
2019-02-28 22:41:04 | stderr | Traceback (most recent call last):
2019-02-28 22:41:04 | stderr | File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 384, in _make_request
2019-02-28 22:41:04 | stderr | six.raise_from(e, None)
2019-02-28 22:41:04 | stderr | File "<string>", line 2, in raise_from
2019-02-28 22:41:04 | stderr | File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 380, in _make_request
2019-02-28 22:41:04 | stderr | httplib_response = conn.getresponse()
2019-02-28 22:41:04 | stderr | File "/usr/local/lib/python3.7/http/client.py", line 1321, in getresponse
2019-02-28 22:41:04 | stderr | response.begin()
2019-02-28 22:41:04 | stderr | File "/usr/local/lib/python3.7/http/client.py", line 296, in begin
2019-02-28 22:41:04 | stderr | version, status, reason = self._read_status()
2019-02-28 22:41:04 | stderr | File "/usr/local/lib/python3.7/http/client.py", line 257, in _read_status
2019-02-28 22:41:04 | stderr | line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
2019-02-28 22:41:04 | stderr | File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
2019-02-28 22:41:04 | stderr | return self._sock.recv_into(b)
2019-02-28 22:41:04 | stderr | socket.timeout: timed out
2019-02-28 22:41:04 | stderr |  
2019-02-28 22:41:04 | stderr | During handling of the above exception, another exception occurred:
2019-02-28 22:41:04 | stderr |  
2019-02-28 22:41:04 | stderr | Traceback (most recent call last):
2019-02-28 22:41:04 | stderr | File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
2019-02-28 22:41:04 | stderr | timeout=timeout
2019-02-28 22:41:04 | stderr | File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
2019-02-28 22:41:04 | stderr | _stacktrace=sys.exc_info()[2])
2019-02-28 22:41:04 | stderr | File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 367, in increment
2019-02-28 22:41:04 | stderr | raise six.reraise(type(error), error, _stacktrace)
2019-02-28 22:41:04 | stderr | File "/usr/local/lib/python3.7/site-packages/urllib3/packages/six.py", line 686, in reraise
2019-02-28 22:41:04 | stderr | raise value
2019-02-28 22:41:04 | stderr | File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
2019-02-28 22:41:04 | stderr | chunked=chunked)
2019-02-28 22:41:04 | stderr | File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 386, in _make_request
2019-02-28 22:41:04 | stderr | self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
2019-02-28 22:41:04 | stderr | File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
2019-02-28 22:41:04 | stderr | raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
2019-02-28 22:41:04 | stderr | urllib3.exceptions.ReadTimeoutError: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
2019-02-28 22:41:04 | stderr |  
2019-02-28 22:41:04 | stderr | During handling of the above exception, another exception occurred:
2019-02-28 22:41:04 | stderr |  
2019-02-28 22:41:04 | stderr | Traceback (most recent call last):
2019-02-28 22:41:04 | stderr | File "/usr/local/lib/python3.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
2019-02-28 22:41:04 | stderr | retval = job.func(*job.args, **job.kwargs)
2019-02-28 22:41:04 | stderr | File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 321, in update
2019-02-28 22:41:04 | stderr | self.recreate(container, latest_image)
2019-02-28 22:41:04 | stderr | File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 137, in recreate
2019-02-28 22:41:04 | stderr | self.remove(container)
2019-02-28 22:41:04 | stderr | File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 128, in remove
2019-02-28 22:41:04 | stderr | container.remove()
2019-02-28 22:41:04 | stderr | File "/usr/local/lib/python3.7/site-packages/docker/models/containers.py", line 339, in remove
2019-02-28 22:41:04 | stderr | return self.client.api.remove_container(self.id, **kwargs)
2019-02-28 22:41:04 | stderr | File "/usr/local/lib/python3.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
2019-02-28 22:41:04 | stderr | return f(self, resource_id, *args, **kwargs)
2019-02-28 22:41:04 | stderr | File "/usr/local/lib/python3.7/site-packages/docker/api/container.py", line 990, in remove_container
2019-02-28 22:41:04 | stderr | self._url("/containers/{0}", container), params=params
2019-02-28 22:41:04 | stderr | File "/usr/local/lib/python3.7/site-packages/docker/utils/decorators.py", line 46, in inner
2019-02-28 22:41:04 | stderr | return f(self, *args, **kwargs)
2019-02-28 22:41:04 | stderr | File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 233, in _delete
2019-02-28 22:41:04 | stderr | return self.delete(url, **self._set_request_timeout(kwargs))
2019-02-28 22:41:04 | stderr | File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 615, in delete
2019-02-28 22:41:04 | stderr | return self.request('DELETE', url, **kwargs)
2019-02-28 22:41:04 | stderr | File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
2019-02-28 22:41:04 | stderr | resp = self.send(prep, **send_kwargs)
2019-02-28 22:41:04 | stderr | File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
2019-02-28 22:41:04 | stderr | r = adapter.send(request, **kwargs)
2019-02-28 22:41:04 | stderr | File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 529, in send
2019-02-28 22:41:04 | stderr | raise ReadTimeout(e, request=request)
-- | -- | --
2019-02-28 22:41:04 | stderr | requests.exceptions.ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
```
(Flipped the line order - DirtyCajunRice)
Is this expected behaviour? And can I assume it is still doing it's job at this point?

My docker run:
```
sudo docker run -d \
  --name ouroboros \
  -e INTERVAL=45000 \
  -e LOGLEVEL=info \
  -e SELF_UPDATE=true \
  -e RUNONCE=false \
  -e CLEANUP=true \
  -e TZ=Europe/Berlin \
  -v /var/run/docker.sock:/var/run/docker.sock \
  --restart unless-stopped \
pyouroboros/ouroboros
```

**Comment by DirtyCajunRice** [comment]
This has nothing to do with us. Ouroboros lost connection to the docker socket as it was unavailable for some extended period of time. I flipped the line order for you too

**Comment by imbaimbaimba** [comment]
> This has nothing to do with us. Ouroboros lost connection to the docker socket as it was unavailable for some extended period of time. I flipped the line order for you too

Ok, sorry I did not mean to imply that it was anything to do with you. It seems something is causing incompatibility. I have no idea how docker socket works or anything like that. But at the same time I get these exceptions, my KODI Driver for my remote(running Node v6) also crashes:
```
Kodi Driver by Niels de Klerk.
Updater registered.
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:1337
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at net.js:1408:9
    at _combinedTickCallback (internal/process/next_tick.js:83:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```
If you by chance could help point me in any sort of the right direction, I would highly appreciate it.

**Comment by DirtyCajunRice** [comment]
the issues section isnt the place for this. hop in discord if you can
