### ISSUE TITLE
socket.timeout error catch needed

### ISSUE THREAD

**Issue by hexeth** [pyouroboros/ouroboros#252]
```2019-03-04 03:04:55 : ERROR : base : Job "Cron container update for unix://var/run/docker.sock (trigger: cron[month='*', day='*', day_of_week='*', hour='3', minute='0'], next run at: 2019-03-05 03:00:00 PST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out```

per @DirtyCajunRice "Per dirtycajun catch the error so it can try again next pass"

**Comment by circa10a** [comment]
@DirtyCajunRice where should this catch take place?

**Comment by DirtyCajunRice** [comment]
i would assume at the dockerclient

**Comment by DirtyCajunRice** [comment]
After looking closer at this is there is not a "right" place to catch this. I would need more traceback than just that section to see where i can catch it on our end
