### ISSUE TITLE
"Driver devicemapper failed to remove root filesystem" when updating container

### ISSUE THREAD

**Issue by wizzy99** [pyouroboros/ouroboros#257]
This is happening pretty much every time a container is updated; this is the third one today.  I have to manually remove the directory from /var/lib/docker/devicemapper/mnt, remove the container, and then restart it to bring it back up.  Ideas?

2019-03-06 15:24:23 : INFO : **ouroboros : Version: 1.3.1-master,**
2019-03-08 15:27:37 : ERROR : base : Job "Interval container update for unix://var/run/docker.sock (trigger: interval[1 day, 0:00:00], next run at: 2019-03-09 15:24:24 EST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 256, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.35/containers/f9887cf6c6cd5669c180dd4cc15e86174c99a9264b95985bbcaca8008f54eb70?v=False&link=False&force=False

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 321, in update
    self.recreate(container, latest_image)
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 137, in recreate
    self.remove(container)
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 128, in remove
    container.remove()
  File "/usr/local/lib/python3.7/site-packages/docker/models/containers.py", line 339, in remove
    return self.client.api.remove_container(self.id, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/docker/api/container.py", line 992, in remove_container
    self._raise_for_status(res)
  File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 258, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python3.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("Driver devicemapper failed to remove root filesystem f9887cf6c6cd5669c180dd4cc15e86174c99a9264b95985bbcaca8008f54eb70: failed to remove device b27fc5c1bdc262f0f31fcde5b80853b45b47cd79684f0cf45bbb4fdcfdf20b08: Device is Busy")

**Comment by circa10a** [comment]
This sounds more like a docker filesystem issue than it is an ouroboros issue

**Comment by circa10a** [comment]
This is a docker issue, not ouroboros. Ouroboros is just a docker orchestrator.
Reference:
https://github.com/moby/moby/issues/27381
