### ISSUE TITLE
Self update errors. Not deleting old self

### ISSUE THREAD

**Issue by p0rkjello** [pyouroboros/ouroboros#262]
Found a second ouroboros container running this morning.

**Process:**
```
$ docker ps | grep ouroboros
0f5aaa1e2dba        pyouroboros/ouroboros:latest          "ouroboros"         11 hours ago        Up 11 hours          ouroboros
477ebd0ff633        pyouroboros/ouroboros:latest          "ouroboros"         11 hours ago        Up 11 hours          ouroboros-updated
```

**Logs:**
```
$ docker-compose logs
Attaching to ouroboros, ouroboros-updated
ouroboros    | 2019-03-10 20:47:04 : INFO : ouroboros : Version: 1.3.1-master
ouroboros    | 2019-03-10 20:47:05 : ERROR : base : Job "Self Check for unix://var/run/docker.sock (trigger: date[2019-03-10 20:47:05 EDT], next run at: 2019-03-10 20:47:05 EDT)" raised an exception
ouroboros    | Traceback (most recent call last):
ouroboros    |   File "/usr/local/lib/python3.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
ouroboros    |     retval = job.func(*job.args, **job.kwargs)
ouroboros    |   File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 235, in self_check
ouroboros    |     self.update_self(count=2, me_list=me_list)
ouroboros    |   File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 350, in update_self
ouroboros    |     old_me_id = me_list[0]['Id'] if me_list[0]['Created'] < me_list[1]['Created'] else me_list[1]['Id']
ouroboros    | TypeError: 'Container' object is not subscriptable
ouroboros-updated | 2019-03-10 20:46:49 : INFO : ouroboros : Version: 1.3.1-master
ouroboros-updated | 2019-03-10 20:46:50 : ERROR : base : Job "Self Check for unix://var/run/docker.sock (trigger: date[2019-03-10 20:46:50 EDT], next run at: 2019-03-10 20:46:50 EDT)" raised an exception
ouroboros-updated | Traceback (most recent call last):
ouroboros-updated |   File "/usr/local/lib/python3.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
ouroboros-updated |     retval = job.func(*job.args, **job.kwargs)
ouroboros-updated |   File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 235, in self_check
ouroboros-updated |     self.update_self(count=2, me_list=me_list)
ouroboros-updated |   File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 350, in update_self
ouroboros-updated |     old_me_id = me_list[0]['Id'] if me_list[0]['Created'] < me_list[1]['Created'] else me_list[1]['Id']
ouroboros-updated | TypeError: 'Container' object is not subscriptable
ouroboros-updated | 2019-03-10 20:46:53 : ERROR : dockerclient : Self update failed.
ouroboros-updated | 2019-03-10 20:46:53 : ERROR : dockerclient : 409 Client Error: Conflict ("Conflict. The container name "/ouroboros-updated" is already in use by container "477ebd0ff6334146efae6a2ec613b58d56040822ce8464ef2fee60a03b88586f". You have to remove (or rename) that container to be able to reuse that name.")
ouroboros-updated | 2019-03-10 20:46:53 : INFO : dockerclient : ouroboros will be updated
```

**Config:**
```
$ docker-compose config
networks:
  default:
    external:
      name: core
services:
  ouroboros:
    container_name: ouroboros
    environment:
      CLEANUP: "true"
      IGNORE: mongo influxdb postgres mariadb
      INTERVAL: '43200'
      LOG_LEVEL: info
      SELF_UPDATE: "true"
      TZ: America/New_York
    hostname: ouroboros
    image: pyouroboros/ouroboros
    restart: unless-stopped
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:rw
version: '3.5'
```

**Comment by bilago** [comment]
I also confirm this bug:

https://i.imgur.com/YKscFmp.png

**Comment by DirtyCajunRice** [comment]
yeah we are aware. its specific to cron users. Still dont know the best way to address it yet

**Comment by DirtyCajunRice** [comment]
yes if you do that it will update again as expected

**Comment by p0rkjello** [comment]
> yeah we are aware. its specific to cron users. Still dont know the best way to address it yet

I was using `INTERVAL: '43200' at the time of the error.

**Comment by DirtyCajunRice** [comment]
hmm thats odd. it should run immediately and clean up.

**Comment by bilago** [comment]
I'm also not using cron to update the container, using interval as well

**Comment by DirtyCajunRice** [comment]
can yall give a full output of the docker logs for both the old instance as it dies and the first update? would reallly help us

**Comment by DirtyCajunRice** [comment]
Should be fixed in dev after the pr

**Comment by rcdailey** [comment]
I just saw this today on `1.4.2-master`. I did a compose down & up to fix it, but I am not sure why it happened in the first place. If this happens again, is it related to this issue? Is there some diagnostic I can provide to help you diagnose the issue?
