### ISSUE TITLE
Auto update doesn’t run the container 

### ISSUE THREAD

**Issue by lilarcor** [pyouroboros/ouroboros#264]
My image gets updated by ourobros, but the container shows it’s created but not running. And sometime , container can’t start, then I hvae to remove and recreate it.

**Comment by circa10a** [comment]
Do you have any debug output?

**Comment by DirtyCajunRice** [comment]
Closing as there has been no progress. If you find time to reply let us know

**Comment by lilarcor** [comment]
sorry for the late
`    network.connect(**new_network_config),
  File "/usr/local/lib/python3.7/site-packages/docker/models/networks.py", line 57, in connect,
    container, self.id, *args, **kwargs,
  File "/usr/local/lib/python3.7/site-packages/docker/utils/decorators.py", line 19, in wrapped,
    return f(self, resource_id, *args, **kwargs),
  File "/usr/local/lib/python3.7/site-packages/docker/api/network.py", line 242, in connect_container_to_network,
    ipv6_address=ipv6_address, link_local_ips=link_local_ips,
  File "/usr/local/lib/python3.7/site-packages/docker/api/container.py", line 649, in create_endpoint_config,
    return EndpointConfig(self._version, *args, **kwargs),
  File "/usr/local/lib/python3.7/site-packages/docker/types/networks.py", line 17, in __init__,
    self["Links"] = normalize_links(links),
  File "/usr/local/lib/python3.7/site-packages/docker/utils/utils.py", line 447, in normalize_links,
    return ['{0}:{1}'.format(k, v) if v else k for k, v in sorted(links)],
  File "/usr/local/lib/python3.7/site-packages/docker/utils/utils.py", line 447, in <listcomp>,
    return ['{0}:{1}'.format(k, v) if v else k for k, v in sorted(links)],
ValueError: too many values to unpack (expected 2),
2019-03-24 20:03:59 : INFO : ouroboros : Version: 1.3.1-master,
2019-03-24 20:04:03 : WARNING : NotifyEmail : A Connection error occured sending Email notification to 192.168.6.98.,
2019-03-26 02:05:30 : INFO : dockerclient : zabbix_sub will be updated,
2019-03-26 02:05:37 : ERROR : base : Job "Interval container update for unix://var/run/docker.sock (trigger: interval[10:00:00], next run at: 2019-03-26 12:04:03 CST)" raised an exception,
Traceback (most recent call last):,
  File "/usr/local/lib/python3.7/site-packages/apscheduler/executors/base.py", line 125, in run_job,
    retval = job.func(*job.args, **job.kwargs),
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 321, in update,
    self.recreate(container, latest_image),
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 157, in recreate,
    network.connect(**new_network_config),
  File "/usr/local/lib/python3.7/site-packages/docker/models/networks.py", line 57, in connect,
    container, self.id, *args, **kwargs,
  File "/usr/local/lib/python3.7/site-packages/docker/utils/decorators.py", line 19, in wrapped,
    return f(self, resource_id, *args, **kwargs),
  File "/usr/local/lib/python3.7/site-packages/docker/api/network.py", line 242, in connect_container_to_network,
    ipv6_address=ipv6_address, link_local_ips=link_local_ips,
  File "/usr/local/lib/python3.7/site-packages/docker/api/container.py", line 649, in create_endpoint_config,
    return EndpointConfig(self._version, *args, **kwargs),
  File "/usr/local/lib/python3.7/site-packages/docker/types/networks.py", line 17, in __init__,
    self["Links"] = normalize_links(links),
  File "/usr/local/lib/python3.7/site-packages/docker/utils/utils.py", line 447, in normalize_links,
    return ['{0}:{1}'.format(k, v) if v else k for k, v in sorted(links)],
  File "/usr/local/lib/python3.7/site-packages/docker/utils/utils.py", line 447, in <listcomp>,
    return ['{0}:{1}'.format(k, v) if v else k for k, v in sorted(links)],
ValueError: too many values to unpack (expected 2),
2019-03-26 22:06:10 : ERROR : dockerclient : Issue detecting aria2_sub's image tag. Skipping...,
2019-03-27 08:05:32 : INFO : dockerclient : gogs_sub will be updated,
2019-03-27 08:05:44 : INFO : NotifyEmail : Sent Email notification to "joey.lu@ecapsul.com".,
2019-03-27 18:09:04 : ERROR : dockerclient : Issue detecting ouroboros_sub's image tag. Skipping...,
2019-03-27 18:09:04 : ERROR : dockerclient : Issue detecting shaarli_sub's image tag. Skipping...,
2019-03-27 18:09:04 : ERROR : dockerclient : Issue detecting portainer_sub's image tag. Skipping...,
2019-03-27 18:10:50 : INFO : dockerclient : redis_sub will be updated,
2019-03-27 18:10:58 : INFO : dockerclient : postgres_sub will be updated,
2019-03-27 18:11:13 : INFO : NotifyEmail : Sent Email notification to "joey.lu@ecapsul.com".,
2019-03-28 04:06:00 : INFO : dockerclient : ttrss_sub will be updated,
2019-03-28 04:06:11 : INFO : dockerclient : nextcloud_sub will be updated,
2019-03-28 04:06:13 : ERROR : base : Job "Interval container update for unix://var/run/docker.sock (trigger: interval[10:00:00], next run at: 2019-03-28 14:04:03 CST)" raised an exception,
Traceback (most recent call last):,
  File "/usr/local/lib/python3.7/site-packages/apscheduler/executors/base.py", line 125, in run_job,
    retval = job.func(*job.args, **job.kwargs),
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 321, in update,
    self.recreate(container, latest_image),
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 157, in recreate,
    network.connect(**new_network_config),
  File "/usr/local/lib/python3.7/site-packages/docker/models/networks.py", line 57, in connect,
    container, self.id, *args, **kwargs,
  File "/usr/local/lib/python3.7/site-packages/docker/utils/decorators.py", line 19, in wrapped,
    return f(self, resource_id, *args, **kwargs),
  File "/usr/local/lib/python3.7/site-packages/docker/api/network.py", line 242, in connect_container_to_network,
    ipv6_address=ipv6_address, link_local_ips=link_local_ips,
  File "/usr/local/lib/python3.7/site-packages/docker/api/container.py", line 649, in create_endpoint_config,
    return EndpointConfig(self._version, *args, **kwargs),
  File "/usr/local/lib/python3.7/site-packages/docker/types/networks.py", line 17, in __init__,
    self["Links"] = normalize_links(links),
  File "/usr/local/lib/python3.7/site-packages/docker/utils/utils.py", line 447, in normalize_links,
    return ['{0}:{1}'.format(k, v) if v else k for k, v in sorted(links)],
  File "/usr/local/lib/python3.7/site-packages/docker/utils/utils.py", line 447, in <listcomp>,
    return ['{0}:{1}'.format(k, v) if v else k for k, v in sorted(links)],
ValueError: too many values to unpack (expected 2),
2019-03-28 14:06:12 : INFO : dockerclient : wordpress_sub will be updated,
2019-03-28 14:06:16 : ERROR : base : Job "Interval container update for unix://var/run/docker.sock (trigger: interval[10:00:00], next run at: 2019-03-29 00:04:03 CST)" raised an exception,
Traceback (most recent call last):,
  File "/usr/local/lib/python3.7/site-packages/apscheduler/executors/base.py", line 125, in run_job,
    retval = job.func(*job.args, **job.kwargs),
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 321, in update,
    self.recreate(container, latest_image),
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 157, in recreate,
    network.connect(**new_network_config),
  File "/usr/local/lib/python3.7/site-packages/docker/models/networks.py", line 57, in connect,
    container, self.id, *args, **kwargs,
  File "/usr/local/lib/python3.7/site-packages/docker/utils/decorators.py", line 19, in wrapped,
    return f(self, resource_id, *args, **kwargs),
  File "/usr/local/lib/python3.7/site-packages/docker/api/network.py", line 242, in connect_container_to_network,
    ipv6_address=ipv6_address, link_local_ips=link_local_ips,
  File "/usr/local/lib/python3.7/site-packages/docker/api/container.py", line 649, in create_endpoint_config,
    return EndpointConfig(self._version, *args, **kwargs),
  File "/usr/local/lib/python3.7/site-packages/docker/types/networks.py", line 17, in __init__,
    self["Links"] = normalize_links(links),
  File "/usr/local/lib/python3.7/site-packages/docker/utils/utils.py", line 447, in normalize_links,
    return ['{0}:{1}'.format(k, v) if v else k for k, v in sorted(links)],
  File "/usr/local/lib/python3.7/site-packages/docker/utils/utils.py", line 447, in <listcomp>,
    return ['{0}:{1}'.format(k, v) if v else k for k, v in sorted(links)],
ValueError: too many values to unpack (expected 2),`
