### ISSUE TITLE
Uncaught stacktrace when checking a swarm service image from AWS ECR

### ISSUE THREAD

**Issue by molexx** [pyouroboros/ouroboros#287]
Received this error when checking a swarm service.
I'm investigating the cause but @DirtyCajunRice asked to report the stacktrace so it can be handled.

```
2019-04-10 16:52:07 : DEBUG : dockerclient : Checking tag: xxxx.dkr.ecr.us-west-2.amazonaws.com/xxxx:develop-latest
2019-04-10 16:52:07 : DEBUG : auth : Looking for auth config
2019-04-10 16:52:07 : DEBUG : auth : No auth config in memory - loading from filesystem
2019-04-10 16:52:07 : DEBUG : config : Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2019-04-10 16:52:07 : DEBUG : config : No config file found
2019-04-10 16:52:07 : DEBUG : auth : Looking for auth entry for 'xxxx.dkr.ecr.us-west-2.amazonaws.com'
2019-04-10 16:52:07 : DEBUG : auth : No entry found
2019-04-10 16:52:07 : DEBUG : auth : No auth config found
2019-04-10 16:52:07 : DEBUG : connectionpool : http://localhost:None "POST /v1.35/images/create?tag=develop-latest&fromImage=xxxx.dkr.ecr.us-west-2.amazonaws.com%2Fxxxx HTTP/1.1" 500 146
2019-04-10 16:52:07 : ERROR : base : Job "Interval container update for unix://var/run/docker.sock (trigger: interval[0:01:00], next run at: 2019-04-10 16:53:07 UTC)" raised an exception
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
retval = job.func(*job.args, **job.kwargs)
File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 426, in update
latest_image_sha256 = get_digest(latest_image)
File "/usr/local/lib/python3.7/site-packages/pyouroboros/helpers.py", line 35, in get_digest
digest = image.attrs.get(
AttributeError: 'NoneType' object has no attribute 'attrs'
```

**Comment by molexx** [comment]
Confirming the problem was lack of auth details causing the POST to the docker API to return 500 rather than image details.

So I think this ticket is to catch the 500 and/or the null image before trying to check its attributes.

**Comment by DirtyCajunRice** [comment]
Interesting... it shouldnt even get that far with a 500. Ill look into it when i get a chance. Good find.
