### ISSUE TITLE
Read timed out. (read timeout=70)

### ISSUE THREAD

**Issue by grewhit25** [pyouroboros/ouroboros#293]
# Read timed out. (read timeout=70)

I received the error below last night during a cron scheduled run at 04:00 in the morning.
The issue is same as that reported in [#290](https://github.com/pyouroboros/ouroboros/issues/290) but that is closed with the suggestion that the system may have been too busy at the time causing the timeout to mature.

I have taken that suggestion on board and have added [stop_grace_period](https://docs.docker.com/compose/compose-file/#stop_grace_period) to my Docker Compose file.

Question: Can/will ouroboros honor the stop grace period to help prevent/minimize this type of issue?

My hardware configuration.

Raspberry Pi 3 Model B+ Rev a020d3
OS Raspbian Lite
Linux 4.14.98-v7+ #1200 SMP Tue Feb 12 20:27:48 GMT 2019 armv7l GNU/Linux
Docker Version:  18.09.0
ouroboros -v: 1.3.1

<details>
<summary> 
Ouroboros error log
</summary>

```logs
2019-04-24 04:30:51 : INFO : dockerclient : home-assistant will be updated
2019-04-24 04:30:51 : DEBUG : dockerclient : Stopping container: home-assistant
2019-04-24 04:32:13 : ERROR : base : Job "Cron container update for unix://var/run/docker.sock (trigger: cron[month='*', day='*', day_of_week='*', hour='4', minute='7'], next run at: 2019-04-25 04:07:00 BST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.7/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=70)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 321, in update
    self.recreate(container, latest_image)
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 136, in recreate
    self.stop(container)
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 123, in stop
    container.stop()
  File "/usr/local/lib/python3.7/site-packages/docker/models/containers.py", line 424, in stop
    return self.client.api.stop(self.id, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/docker/api/container.py", line 1149, in stop
    res = self._post(url, params=params, timeout=conn_timeout)
  File "/usr/local/lib/python3.7/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 221, in _post
    return self.post(url, **self._set_request_timeout(kwargs))
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=70)
```

</details>

**Comment by DirtyCajunRice** [comment]
It is not a docker container issue, it is a docker daemon issue. the entire daemon is unresponsive. we cant fix something we cant access :(.

**Comment by nicx** [comment]
@DirtyCajunRice is it possible to make the value for read timeout configurable? Unfortunately I have different cases when 60 is too less for me :(
