### ISSUE TITLE
When running for some time, crashes with ConnectionRefusedError: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by itsthejb** [pyouroboros/ouroboros#300]
Hi all,

This is a great tool, and very happy to replace Watchtower. However, when the container is left running for some time, it will eventually start crashing with:

```
2019-04-27 06:00:19 : ERROR : base : Job "Cron container update for unix://var/run/docker.sock (trigger: cron[month='*', day='*', day_of_week='*', hour='6', minute='0'], next run at: 2019-04-28 06:00:00 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/docker/transport/unixconn.py", line 42, in connect
    sock.connect(self.unix_socket)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.7/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/docker/transport/unixconn.py", line 42, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 296, in update
    updateable, depends_on_containers, hard_depends_on_containers = self.socket_check()
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 241, in socket_check
    self.monitored = self.monitor_filter()
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 207, in monitor_filter
    running_containers = self.running_filter()
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 185, in running_filter
    for container in self.client.containers.list(filters={'status': 'running'}):
  File "/usr/local/lib/python3.7/site-packages/docker/models/containers.py", line 918, in list
    since=since)
  File "/usr/local/lib/python3.7/site-packages/docker/api/container.py", line 208, in containers
    res = self._result(self._get(u, params=params), True)
  File "/usr/local/lib/python3.7/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 225, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionRefusedError(111, 'Connection refused'))
```

I believe if the container is restarted it will work for a while, but this will eventually reoccur. Using the official `pyouroboros/ouroboros` container.

Hope someone can help!

**Comment by DirtyCajunRice** [comment]
What is it running on (os)? it looks like it loses the connection to your docker socket from initial inspection

**Comment by itsthejb** [comment]
Hi there,

`CentOS Linux release 7.6.1810 (Core)`. I've actually moved to using Ouroboros via Cron with `RUN_ONCE`, which seems to work nicely. However, perhaps I can help somehow if this is a genuine issue?

**Comment by Ezwen** [comment]
Same errors here using Debian 9.

**Comment by MarkusFreitag** [comment]
I'm experiencing the same issue using the official `pyouroboros/ouroboros` container. Once it is running for a while, it eventually starts logging these errors.
