### ISSUE TITLE
Update of a container runs into Traceback

### ISSUE THREAD

**Issue by schmic** [pyouroboros/ouroboros#311]
```
Attaching to middleware-updater_ouro_1
ouro_1  | 2019-05-23 12:19:06 : INFO : ouroboros : Version: 1.4.0-master
ouro_1  | 2019-05-23 12:24:21 : INFO : dockerclient : sap_tomee_1 will be updated
ouro_1  | 2019-05-23 12:24:32 : ERROR : base : Job "Interval container update for unix://var/run/docker.sock (trigger: interval[0:05:00], next run at: 2019-05-23 12:29:06 UTC)" raised an exception
ouro_1  | Traceback (most recent call last):
ouro_1  |   File "/usr/local/lib/python3.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
ouro_1  |     retval = job.func(*job.args, **job.kwargs)
ouro_1  |   File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 326, in update
ouro_1  |     self.recreate(container, latest_image)
ouro_1  |   File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 162, in recreate
ouro_1  |     network.connect(**new_network_config)
ouro_1  |   File "/usr/local/lib/python3.7/site-packages/docker/models/networks.py", line 57, in connect
ouro_1  |     container, self.id, *args, **kwargs
ouro_1  |   File "/usr/local/lib/python3.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
ouro_1  |     return f(self, resource_id, *args, **kwargs)
ouro_1  |   File "/usr/local/lib/python3.7/site-packages/docker/api/network.py", line 242, in connect_container_to_network
ouro_1  |     ipv6_address=ipv6_address, link_local_ips=link_local_ips
ouro_1  |   File "/usr/local/lib/python3.7/site-packages/docker/api/container.py", line 649, in create_endpoint_config
ouro_1  |     return EndpointConfig(self._version, *args, **kwargs)
ouro_1  |   File "/usr/local/lib/python3.7/site-packages/docker/types/networks.py", line 17, in __init__
ouro_1  |     self["Links"] = normalize_links(links)
ouro_1  |   File "/usr/local/lib/python3.7/site-packages/docker/utils/utils.py", line 445, in normalize_links
ouro_1  |     return ['{0}:{1}'.format(k, v) if v else k for k, v in sorted(links)]
ouro_1  |   File "/usr/local/lib/python3.7/site-packages/docker/utils/utils.py", line 445, in <listcomp>
ouro_1  |     return ['{0}:{1}'.format(k, v) if v else k for k, v in sorted(links)]
ouro_1  | ValueError: too many values to unpack (expected 2)
```

**Comment by schmic** [comment]
Seems to be a duplicated of  #225

Though using a network is not an option at the moment, I need to link various containers with a stable name ...
