### ISSUE TITLE
Could not connect to socket ********unix://********.sock. Check your config

### ISSUE THREAD

**Issue by IceCloud76** [pyouroboros/ouroboros#317]
For some reason, Ouroboros can't connect to the docker socket. Still a bit new to Docker as a whole, but I haven't messed with any configs yet and I checked and it is still under /var/run/docker.sock

After a docker pull, I ran `docker run -d --name ouroboros \
  -v /var/run/docker.sock:/var/run/docker.sock \
  pyouroboros/ouroboros` to start the container as usual.

But when I tried to do a dry run with `docker run --rm pyouroboros/ouroboros -o -A`, I got this:
`ERROR : ouroboros : Could not connect to socket ********.sock. Check your config`

When changing the log level to debug, I immediately got this:
`2019-06-05 15:40:44 : INFO : ouroboros : Version: 1.4.1-master
2019-06-05 15:40:44 : DEBUG : ouroboros : Ouroboros configuration: {'interval': 300, 'docker_sockets': ['unix://var/run/docker.sock'], 'log_level': 'debug', 'prometheus_addr': None, 'prometheus_port': None, 'influx_url': None, 'influx_port': None, 'influx_username': None, 'influx_password': None, 'hostname': '5a449f01ef69', 'docker_tls_verify': True}
2019-06-05 15:40:44 : INFO : base : Scheduler started
2019-06-05 15:40:44 : DEBUG : base : Looking for jobs to run
2019-06-05 15:40:44 : DEBUG : config : Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2019-06-05 15:40:44 : DEBUG : base : No jobs; waiting until a job is added
2019-06-05 15:40:44 : DEBUG : config : No config file found
2019-06-05 15:40:44 : DEBUG : config : Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2019-06-05 15:40:44 : DEBUG : config : No config file found
2019-06-05 15:40:44 : ERROR : ouroboros : Could not connect to socket ********.sock. Check your config
2019-06-05 15:40:44 : INFO : base : Scheduler has been shut down
2019-06-05 15:40:44 : DEBUG : base : Looking for jobs to run
2019-06-05 15:40:44 : DEBUG : base : No jobs; waiting until a job is added`

All I can tell is that it seems some config file is missing, but I'm not sure what I need or what to do at this point. I've tried reinstating the container with the same docker run command, but I've had no luck. Any help would be appreciated.

System: Ubuntu 18.04 LTS
Docker version:  Docker version 18.09.5, build e8ff056
ouroboros is version 1.4.1
I'll gladly provide any addition details if I'm missing something

**Comment by DirtyCajunRice** [comment]
the second run command isnt attaching the docker socket like the first is.

**Comment by IceCloud76** [comment]
> I've tried reinstating the container with the same docker run command

I mean the first run command in my post. The first run command in my post creates the container based on the latest image, and this is what I tried again after stopping and removing the existing container.

**Comment by Ylawy** [comment]
I'm experiencing a similar issue since the latest upate.

`

date | stream | content
-- | -- | --
2019-06-06 10:19:28 | stderr | AttributeError: 'Config' object has no attribute 'docker_socket'
2019-06-06 10:19:28 | stderr | self.logger.critical("Can't connect to Docker API at %s", self.config.docker_socket)
2019-06-06 10:19:28 | stderr | File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 205, in running_filter
2019-06-06 10:19:28 | stderr | running_containers = self.running_filter()
2019-06-06 10:19:28 | stderr | File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 212, in monitor_filter
2019-06-06 10:19:28 | stderr | self.monitored = self.monitor_filter()
2019-06-06 10:19:28 | stderr | File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 109, in __init__
2019-06-06 10:19:28 | stderr | mode = Container(docker)
2019-06-06 10:19:28 | stderr | File "/usr/local/lib/python3.7/site-packages/pyouroboros/ouroboros.py", line 161, in main
2019-06-06 10:19:28 | stderr | main()
2019-06-06 10:19:28 | stderr | File "/usr/local/bin/ouroboros", line 5, in <module>
2019-06-06 10:19:28 | stderr | Traceback (most recent call last):
2019-06-06 10:19:28 | stderr |  
2019-06-06 10:19:28 | stderr | During handling of the above exception, another exception occurred:
2019-06-06 10:19:28 | stderr |  
2019-06-06 10:19:28 | stderr | docker.errors.ImageNotFound: 404 Client Error: Not Found ("no such image: 66615de114f76e0f2084791c9fdaab3b8a5e33a7f156aaea3ecbe43054ba4e5a: No such image: sha256:66615de114f76e0f2084791c9fdaab3b8a5e33a7f156aaea3ecbe43054ba4e5a")
2019-06-06 10:19:28 | stderr | raise cls(e, response=response, explanation=explanation)
2019-06-06 10:19:28 | stderr | File "/usr/local/lib/python3.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
2019-06-06 10:19:28 | stderr | raise create_api_error_from_http_exception(e)
2019-06-06 10:19:28 | stderr | File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 263, in _raise_for_status
2019-06-06 10:19:28 | stderr | self._raise_for_status(response)
2019-06-06 10:19:28 | stderr | File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 267, in _result
2019-06-06 10:19:28 | stderr | self._get(self._url("/images/{0}/json", image)), True
2019-06-06 10:19:28 | stderr | File "/usr/local/lib/python3.7/site-packages/docker/api/image.py", line 245, in inspect_image
2019-06-06 10:19:28 | stderr | return f(self, resource_id, *args, **kwargs)
2019-06-06 10:19:28 | stderr | File "/usr/local/lib/python3.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
2019-06-06 10:19:28 | stderr | return self.prepare_model(self.client.api.inspect_image(name))
2019-06-06 10:19:28 | stderr | File "/usr/local/lib/python3.7/site-packages/docker/models/images.py", line 316, in get
2019-06-06 10:19:28 | stderr | return self.client.images.get(image_id.split(':')[1])
2019-06-06 10:19:28 | stderr | File "/usr/local/lib/python3.7/site-packages/docker/models/containers.py", line 40, in image
2019-06-06 10:19:28 | stderr | if 'ouroboros' not in container.image.tags[0]:
2019-06-06 10:19:28 | stderr | File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 195, in running_filter
2019-06-06 10:19:28 | stderr | Traceback (most recent call last):
2019-06-06 10:19:28 | stderr |  
2019-06-06 10:19:28 | stderr | During handling of the above exception, another exception occurred:
2019-06-06 10:19:28 | stderr |  
2019-06-06 10:19:28 | stderr | requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.35/images/66615de114f76e0f2084791c9fdaab3b8a5e33a7f156aaea3ecbe43054ba4e5a/json
2019-06-06 10:19:28 | stderr | raise HTTPError(http_error_msg, response=self)
2019-06-06 10:19:28 | stderr | File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
2019-06-06 10:19:28 | stderr | response.raise_for_status()
2019-06-06 10:19:28 | stderr | File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 261, in _raise_for_status
2019-06-06 10:19:28 | stderr | Traceback (most recent call last):
2019-06-06 10:19:28 | stderr | 2019-06-06 10:19:28 : INFO : ouroboros : Version: 1.4.1-master

`

**Comment by nodecentral** [comment]
Hi

Just tried to install it myself but have the same "cannot connect to socket" error message, and the Container will just not start

**Comment by DirtyCajunRice** [comment]
if it cannot reach the socket, then the socket is not bound. when you run a container from the command line you need to bind on run. even for dry run. your dry run command is not binding.

```docker run --rm \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -e LOG_LEVEL=debug \
    -e  DRY_RUN=true \
    pyouroboros/ouroboros:latest ```

the above works.

**Comment by Ylawy** [comment]
If i try to start the container with the following comand mentioned above I get the error message below.

`docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -e LOG_LEVEL=debug -e DRY_RUN=true pyouroboros/ouroboros:latest`

`2019-06-10 12:33:23 : INFO : ouroboros : Version: 1.4.1-master
2019-06-10 12:33:23 : WARNING : config : Dry run is designed to be ran with run once. Setting for you.
2019-06-10 12:33:23 : DEBUG : ouroboros : Ouroboros configuration: {'interval': 300, 'docker_sockets': ['unix://var/run/docker.sock'], 'log_level': 'debug', 'prometheus_addr': None, 'prometheus_port': None, 'influx_url': None, 'influx_port': None, 'influx_username': None, 'influx_password': None, 'dry_run': True, 'hostname': 'f4b1e73d3fdd', 'docker_tls_verify': True, 'run_once': True}
2019-06-10 12:33:23 : INFO : base : Scheduler started
2019-06-10 12:33:23 : DEBUG : base : Looking for jobs to run
2019-06-10 12:33:23 : DEBUG : config : Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2019-06-10 12:33:23 : DEBUG : base : No jobs; waiting until a job is added
2019-06-10 12:33:23 : DEBUG : config : No config file found
2019-06-10 12:33:23 : DEBUG : config : Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2019-06-10 12:33:23 : DEBUG : config : No config file found
2019-06-10 12:33:23 : DEBUG : connectionpool : http://localhost:None "GET /v1.35/containers/json?limit=-1&all=0&size=0&trunc_cmd=0&filters=%7B%22status%22%3A+%5B%22running%22%5D%7D HTTP/1.1" 200 None
2019-06-10 12:33:23 : DEBUG : connectionpool : http://localhost:None "GET /v1.35/containers/f4b1e73d3fdd87306c3c3a778db41b3f07e9936f8467c972089fbcc549574066/json HTTP/1.1" 200 None
2019-06-10 12:33:23 : DEBUG : connectionpool : http://localhost:None "GET /v1.35/containers/4e19ce41a2188511445eaee13de4580bc8a0ce48e1bf156c97c232c0198f1a79/json HTTP/1.1" 200 None
2019-06-10 12:33:23 : DEBUG : connectionpool : http://localhost:None "GET /v1.35/containers/9fb51749accfb338093c9313c35a004d968cec1b4f5a10587f44f52c0e1c6b5b/json HTTP/1.1" 200 None
2019-06-10 12:33:23 : DEBUG : connectionpool : http://localhost:None "GET /v1.35/containers/8fa5cd1acf084135451bcbb2ef25566023361d44cfb7275168dd602661ebda25/json HTTP/1.1" 200 None
2019-06-10 12:33:23 : DEBUG : connectionpool : http://localhost:None "GET /v1.35/containers/377f6589d171d3440270de386e044524e7336f788b142d0ddda6fb3a7a5b7968/json HTTP/1.1" 200 None
2019-06-10 12:33:23 : DEBUG : connectionpool : http://localhost:None "GET /v1.35/containers/4527530a65f6ee6bfd14e30bcbdc956498c8823949736e0a3992cac9ebf8b57b/json HTTP/1.1" 200 None
2019-06-10 12:33:23 : DEBUG : connectionpool : http://localhost:None "GET /v1.35/containers/c98475c76fe9547a6716ba2c6c7f91577b82f93b41fd000d43c08f006f0ddf43/json HTTP/1.1" 200 None
2019-06-10 12:33:23 : DEBUG : connectionpool : http://localhost:None "GET /v1.35/containers/6dcb6de78a3aff38576e3150aa705a5f51a87d59e72f6d1e4320e8ae93f38643/json HTTP/1.1" 200 None
2019-06-10 12:33:23 : DEBUG : connectionpool : http://localhost:None "GET /v1.35/containers/ed468595a1dcc338b90f810a01136f4afbf126636b2517458d6f18a615a0177c/json HTTP/1.1" 200 None
2019-06-10 12:33:23 : DEBUG : connectionpool : http://localhost:None "GET /v1.35/containers/75acece429128738047b30690d75b04337aca9b6f16c4a1a99eb34d6efd1121d/json HTTP/1.1" 200 None
2019-06-10 12:33:23 : DEBUG : connectionpool : http://localhost:None "GET /v1.35/containers/f5caa44452b9e54891b6ec00091b683e812482a82ab06667dec849e5340a012f/json HTTP/1.1" 200 None
2019-06-10 12:33:23 : DEBUG : connectionpool : http://localhost:None "GET /v1.35/containers/c1c1149adc44fc2a150351e2dfdffa7708d17525836f3e0f534c9e68fb7bc575/json HTTP/1.1" 200 None
2019-06-10 12:33:23 : DEBUG : connectionpool : http://localhost:None "GET /v1.35/containers/03a18051a7bc5f56bff22e1e73e09e49c7ea1e8a362ad43d69682f18d7add377/json HTTP/1.1" 200 None
2019-06-10 12:33:23 : DEBUG : connectionpool : http://localhost:None "GET /v1.35/containers/d425c17a222bec10e64c40cb7c83dc412f998bcf0e47a94c89098328d95aeb62/json HTTP/1.1" 200 None
2019-06-10 12:33:23 : DEBUG : connectionpool : http://localhost:None "GET /v1.35/containers/845db798dbcdd5146f429c1b4cd476600ce1cc2672aa5412bddda6a5c925a73e/json HTTP/1.1" 200 None
2019-06-10 12:33:23 : DEBUG : connectionpool : http://localhost:None "GET /v1.35/images/a0cf0f3311b2ce7bff08e49450d74a220efe215aa61341d08070e8f9a53b5401/json HTTP/1.1" 200 None
2019-06-10 12:33:23 : DEBUG : connectionpool : http://localhost:None "GET /v1.35/images/8123461b175574bdf38dfda1fa3f008b111dd4d1733a1aa0f380e5eec3320d2d/json HTTP/1.1" 200 None
2019-06-10 12:33:23 : DEBUG : connectionpool : http://localhost:None "GET /v1.35/images/8123461b175574bdf38dfda1fa3f008b111dd4d1733a1aa0f380e5eec3320d2d/json HTTP/1.1" 200 None
2019-06-10 12:33:23 : DEBUG : connectionpool : http://localhost:None "GET /v1.35/images/ab0e541949d56c4d3899769a31a4cbda0c3ffa7891f2ebfafa069a4bc998fedc/json HTTP/1.1" 200 None
2019-06-10 12:33:23 : DEBUG : connectionpool : http://localhost:None "GET /v1.35/images/2b2b6a5c543c94a7450e51b442f514af3cdff83c63bfbe5e0b960465349a30ca/json HTTP/1.1" 200 None
2019-06-10 12:33:23 : DEBUG : connectionpool : http://localhost:None "GET /v1.35/images/c0cb35d7f4c58162da1d659e4618b904db96870b17d0db1221eb0b3950015d67/json HTTP/1.1" 200 None
2019-06-10 12:33:24 : DEBUG : connectionpool : http://localhost:None "GET /v1.35/images/f0145e8ff645e363256653bb75c2de79be18eedf6939a09f47d21c9840805e11/json HTTP/1.1" 200 None
2019-06-10 12:33:24 : DEBUG : connectionpool : http://localhost:None "GET /v1.35/images/8983b216205b210ec47acb77beefb0ae349e8a0645a06f5dc28dbe8d916352c6/json HTTP/1.1" 200 None
2019-06-10 12:33:24 : DEBUG : connectionpool : http://localhost:None "GET /v1.35/images/62b90a8c4d0b2babdba4f4bb1594ea94467c07308ba2268a9f7fdfc9ed0c3159/json HTTP/1.1" 200 None
2019-06-10 12:33:24 : DEBUG : connectionpool : http://localhost:None "GET /v1.35/images/6d502c09d03bdd53658b96fce5a873be0ecb47642de259ffc8a9fb96b1167298/json HTTP/1.1" 200 None
2019-06-10 12:33:24 : DEBUG : connectionpool : http://localhost:None "GET /v1.35/images/62fc05ae1abfab75459243989d90f2d29c55c2fb8a8e791c12b92896d4993e15/json HTTP/1.1" 200 None
2019-06-10 12:33:24 : DEBUG : connectionpool : http://localhost:None "GET /v1.35/images/955aa9c00c279c513fe917a251609d8a638be3fc4da8e3b4be651377619ba089/json HTTP/1.1" 200 None
2019-06-10 12:33:24 : DEBUG : connectionpool : http://localhost:None "GET /v1.35/images/26183bfceb069b6feb2f54d86890435e5aa7421be324da3db9171964b7003ac8/json HTTP/1.1" 200 None
2019-06-10 12:33:24 : DEBUG : connectionpool : http://localhost:None "GET /v1.35/images/a3740e67f15af2b6add73c7f038ba0ae26b61e2f2160c0855ab5542f8980d26f/json HTTP/1.1" 200 None
2019-06-10 12:33:24 : DEBUG : connectionpool : http://localhost:None "GET /v1.35/images/66615de114f76e0f2084791c9fdaab3b8a5e33a7f156aaea3ecbe43054ba4e5a/json HTTP/1.1" 404 182
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.35/images/66615de114f76e0f2084791c9fdaab3b8a5e33a7f156aaea3ecbe43054ba4e5a/json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 195, in running_filter
    if 'ouroboros' not in container.image.tags[0]:
  File "/usr/local/lib/python3.7/site-packages/docker/models/containers.py", line 40, in image
    return self.client.images.get(image_id.split(':')[1])
  File "/usr/local/lib/python3.7/site-packages/docker/models/images.py", line 316, in get
    return self.prepare_model(self.client.api.inspect_image(name))
  File "/usr/local/lib/python3.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/docker/api/image.py", line 245, in inspect_image
    self._get(self._url("/images/{0}/json", image)), True
  File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 267, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python3.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.ImageNotFound: 404 Client Error: Not Found ("no such image: 66615de114f76e0f2084791c9fdaab3b8a5e33a7f156aaea3ecbe43054ba4e5a: No such image: sha256:66615de114f76e0f2084791c9fdaab3b8a5e33a7f156aaea3ecbe43054ba4e5a")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/ouroboros", line 5, in <module>
    main()
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/ouroboros.py", line 161, in main
    mode = Container(docker)
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 109, in __init__
    self.monitored = self.monitor_filter()
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 212, in monitor_filter
    running_containers = self.running_filter()
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 205, in running_filter
    self.logger.critical("Can't connect to Docker API at %s", self.config.docker_socket)
AttributeError: 'Config' object has no attribute 'docker_socket'
`

**Comment by circa10a** [comment]
@IceCloud76 are you running this on a system where you need to execute `sudo` to use docker? If that is the case, the issue would be that of permissions.
