### ISSUE TITLE
ERROR : base : Job "Interval container update for unix://var/run/docker.sock (trigger: interval[0:05:00]

### ISSUE THREAD

**Issue by EdwinGarcia** [pyouroboros/ouroboros#319]
I'm unsure if this is a dupe of #225 , but on the off chance it isn't, here it is. I got this on it's first run after using the docker-compose template in the wiki.

```bash
2019-06-14 13:06:19 : ERROR : base : Job "Interval container update for unix://var/run/docker.sock (trigger: interval[0:05:00], next run at: 2019-06-14 13:10:51 CDT)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http+docker://localhost/v1.35/containers/f0b4d8b9a644378e8ad260149c648ac79899fb84ae3c67e056a4712af93dec3a?v=False&link=False&force=False

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 326, in update
    self.recreate(container, latest_image)
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 137, in recreate
    self.remove(container)
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 128, in remove
    container.remove()
  File "/usr/local/lib/python3.7/site-packages/docker/models/containers.py", line 347, in remove
    return self.client.api.remove_container(self.id, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/docker/api/container.py", line 994, in remove_container
    self._raise_for_status(res)
  File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python3.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 409 Client Error: Conflict ("removal of container f0b4d8b9a644378e8ad260149c648ac79899fb84ae3c67e056a4712af93dec3a is already in progress")
```

**Comment by tedrock** [comment]
Similar problem, been using Ouroboros for awhile and noticed it hasn't updated anything for a month.

config:
`  ouroboros:
    image: pyouroboros/ouroboros:latest
    container_name: ouroboros
    environment:
      - TZ=America/Toronto
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --self-update --interval 300 --log-level info --cleanup -N 'slack:///***/#ouroboros'
`

`ouroboros    | 2019-06-16 12:19:55 : ERROR : base : Job "Initial run interval container update for unix://var/run/docker.sock (trigger: date[2019-06-16 12:19:47 EDT], next run at: 2019-06-16 12:19:47 EDT)" raised an exception
ouroboros    | Traceback (most recent call last):
ouroboros    |   File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 261, in _raise_for_status
ouroboros    |     response.raise_for_status()
ouroboros    |   File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
ouroboros    |     raise HTTPError(http_error_msg, response=self)
ouroboros    | requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.35/images/aec5e024cc9df5dee0b08a171f59e210e84cf400fc0686f5a5e43cf00440f278/json
ouroboros    |
ouroboros    | During handling of the above exception, another exception occurred:
ouroboros    |
ouroboros    | Traceback (most recent call last):
ouroboros    |   File "/usr/local/lib/python3.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
ouroboros    |     retval = job.func(*job.args, **job.kwargs)
ouroboros    |   File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 301, in update
ouroboros    |     updateable, depends_on_containers, hard_depends_on_containers = self.socket_check()
ouroboros    |   File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 253, in socket_check
ouroboros    |     current_image = container.image
ouroboros    |   File "/usr/local/lib/python3.7/site-packages/docker/models/containers.py", line 40, in image
ouroboros    |     return self.client.images.get(image_id.split(':')[1])
ouroboros    |   File "/usr/local/lib/python3.7/site-packages/docker/models/images.py", line 316, in get
ouroboros    |     return self.prepare_model(self.client.api.inspect_image(name))
ouroboros    |   File "/usr/local/lib/python3.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
ouroboros    |     return f(self, resource_id, *args, **kwargs)
ouroboros    |   File "/usr/local/lib/python3.7/site-packages/docker/api/image.py", line 245, in inspect_image
ouroboros    |     self._get(self._url("/images/{0}/json", image)), True
ouroboros    |   File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 267, in _result
ouroboros    |     self._raise_for_status(response)
ouroboros    |   File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 263, in _raise_for_status
ouroboros    |     raise create_api_error_from_http_exception(e)
ouroboros    |   File "/usr/local/lib/python3.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
ouroboros    |     raise cls(e, response=response, explanation=explanation)
ouroboros    | docker.errors.ImageNotFound: 404 Client Error: Not Found ("no such image: aec5e024cc9df5dee0b08a171f59e210e84cf400fc0686f5a5e43cf00440f278: No such image: sha256:aec5e024cc9df5dee0b08a171f59e210e84cf400fc0686f5a5e43cf00440f278")
`

**Comment by brightdroid** [comment]
I've a similar issue:
```
2019-07-03 10:00:59 : ERROR : base : Job "Initial run interval container update for unix://var/run/docker.sock (trigger: date[2019-07-03 10:00:37 CEST], next run at: 2019-07-03 10:00:37 CEST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 326, in update
    self.recreate(container, latest_image)
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 162, in recreate
    network.connect(**new_network_config)
  File "/usr/local/lib/python3.7/site-packages/docker/models/networks.py", line 57, in connect
    container, self.id, *args, **kwargs
  File "/usr/local/lib/python3.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/docker/api/network.py", line 242, in connect_container_to_network
    ipv6_address=ipv6_address, link_local_ips=link_local_ips
  File "/usr/local/lib/python3.7/site-packages/docker/api/container.py", line 650, in create_endpoint_config
    return EndpointConfig(self._version, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/docker/types/networks.py", line 17, in __init__
    self["Links"] = normalize_links(links)
  File "/usr/local/lib/python3.7/site-packages/docker/utils/utils.py", line 445, in normalize_links
    return ['{0}:{1}'.format(k, v) if v else k for k, v in sorted(links)]
  File "/usr/local/lib/python3.7/site-packages/docker/utils/utils.py", line 445, in <listcomp>
    return ['{0}:{1}'.format(k, v) if v else k for k, v in sorted(links)]
ValueError: too many values to unpack (expected 2)
```

**Comment by DirtyCajunRice** [comment]
These are all totally separate problems that are completely dissimilar. 
@EdwinGarcia
that issue is a hung removal for whatever reason. Look into changing the sigterm in labels

@tedrock 
1. Use env vars for those commands, the commands are legacy
2. That looks like an image was deleted outside of ouro and it got confused. Ouro is designed to maintain on its own.

@brightdroid 
Looks like you are either using an old version or have something that ouro doesnt support (e.g. shared networking)
