### ISSUE TITLE
Error when recreating container (container ends up stopped with no network)

### ISSUE THREAD

**Issue by jacekowski** [pyouroboros/ouroboros#334]
On latest version, when upgrading composer container it seems to be throwing an error
```


2019-09-05 11:37:10 : ERROR : base : Job "Interval container update for unix://var/run/docker.sock (trigger: interval[0:05:00], next run at: 2019-09-05 11:41:57 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 326, in update
    self.recreate(container, latest_image)
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 162, in recreate
    network.connect(**new_network_config)
  File "/usr/local/lib/python3.7/site-packages/docker/models/networks.py", line 57, in connect
    container, self.id, *args, **kwargs
  File "/usr/local/lib/python3.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/docker/api/network.py", line 242, in connect_container_to_network
    ipv6_address=ipv6_address, link_local_ips=link_local_ips
  File "/usr/local/lib/python3.7/site-packages/docker/api/container.py", line 650, in create_endpoint_config
    return EndpointConfig(self._version, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/docker/types/networks.py", line 17, in __init__
    self["Links"] = normalize_links(links)
  File "/usr/local/lib/python3.7/site-packages/docker/utils/utils.py", line 445, in normalize_links
    return ['{0}:{1}'.format(k, v) if v else k for k, v in sorted(links)]
  File "/usr/local/lib/python3.7/site-packages/docker/utils/utils.py", line 445, in <listcomp>
    return ['{0}:{1}'.format(k, v) if v else k for k, v in sorted(links)]
ValueError: too many values to unpack (expected 2)

```

**Comment by Ezwen** [comment]
Same problem here, I have a container start with an `external_links` clause in its compose file, and this container does not get restarted by ouroboros when the latter tries to update its image. Instead, the same error as the one above appears in the logs of ouroboros.

**Comment by hellofaduck** [comment]
Same problem today, ouroboros can't start graylog container. This is my docker-compose file:

> version: '2'
> services:
>   mongodb:
>     image: mongo:3
>     volumes:
>       - mongo_data:/data/db
>     environment:
>       - TZ=Europe/Moscow
>   elasticsearch:
>     image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.2
>     volumes:
>       - es_data:/usr/share/elasticsearch/data
>     environment:
>       - http.host=0.0.0.0
>       - transport.host=localhost
>       - network.host=0.0.0.0
>       - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
>       - TZ=Europe/Moscow
>     ulimits:
>       memlock:
>         soft: -1
>         hard: -1
>     mem_limit: 1g
>   graylog:
>     image: graylog/graylog:3.1
>     volumes:
>       - graylog_journal:/usr/share/graylog/data/journal
>     environment:
>       # CHANGE ME (must be at least 16 characters)!
>       - GRAYLOG_PASSWORD_SECRET=deleted
>       - GRAYLOG_ROOT_PASSWORD_SHA2=deleted
>       - GRAYLOG_HTTP_EXTERNAL_URI=http://10.10.10.109:9000/
>       - GRAYLOG_ELASTICSEARCH_MAX_TIME_PER_INDEX = 1d
>       - GRAYLOG_ELASTICSEARCH_MAX_NUMBER_OF_INDICES = 30
>       - GRAYLOG_RETENTION_STRATEGY = delete
>       - GRAYLOG_ROOT_TIMEZONE=Europe/Moscow
>       - TZ=Europe/Moscow
>     links:
>       - mongodb:mongo
>       - elasticsearch
>     depends_on:
>       - mongodb
>       - elasticsearch
>     ports:
>       # Graylog web interface and REST API
>       - 9000:9000
>       # Syslog TCP
>       - 1514:1514
>       # Syslog UDP
>       - 1514:1514/udp
>       #xigmanas backup
>       - 1515:1515/udp
>       #xigmanas storage
>       - 1516:1516/udp
>       #cisco wap371
>       - 1517:1517/udp
>       # GELF TCP
>       #- 12201:12201
>       # GELF UDP
>       #- 12201:12201/udp
>       
> volumes:
>   mongo_data:
>     driver: local
>   es_data:
>     driver: local
>   graylog_journal:
>     driver: local

**Comment by Schnilz** [comment]
I just got the same exception when ouroboros was updating nextcloud
