### ISSUE TITLE
Error: client API version: 1.35, server API version: 1.24

### ISSUE THREAD

**Issue by cesalo** [pyouroboros/ouroboros#336]
One of my servers (Fedora) have docker 1.12 and at the moment I can't do a docker upgrade. Any way to setup the variable DOCKER_API_VERSION as a workaround? I tried at bash level before running "ouroboros" but didn't work. Any other ideas?
Thanks.
```
./ouroboros --run-once -l debug -m xxxxxxx
2019-09-15 11:09:05 : INFO : ouroboros : Version: 1.4.2-master
2019-09-15 11:09:05 : DEBUG : ouroboros : Ouroboros configuration: {'interval': 300, 'docker_sockets': ['unix://var/run/docker.sock'], 'monitor': ['jackett'], 'log_level': 'debug', 'prometheus_addr': None, 'prometheus_port': None, 'run_once': True, 'influx_url': None, 'influx_port': None, 'influx_username': None, 'influx_password': None, 'hostname': 'xxxxxxx', 'docker_tls_verify': True}
2019-09-15 11:09:05 : INFO : base : Scheduler started
2019-09-15 11:09:05 : DEBUG : base : Looking for jobs to run
2019-09-15 11:09:05 : DEBUG : config : Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2019-09-15 11:09:05 : DEBUG : base : No jobs; waiting until a job is added
2019-09-15 11:09:05 : DEBUG : config : No config file found
2019-09-15 11:09:05 : DEBUG : config : Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
2019-09-15 11:09:05 : DEBUG : config : No config file found
2019-09-15 11:09:05 : DEBUG : connectionpool : http://localhost:None "GET /v1.35/containers/json?limit=-1&all=0&size=0&trunc_cmd=0&filters=%7B%22status%22%3A+%5B%22running%22%5D%7D HTTP/1.1" 400 95
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.35/containers/json?limit=-1&all=0&size=0&trunc_cmd=0&filters=%7B%22status%22%3A+%5B%22running%22%5D%7D

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pyouroboros/dockerclient.py", line 190, in running_filter
    for container in self.client.containers.list(filters={'status': 'running'}):
  File "/usr/lib/python3.6/site-packages/docker/models/containers.py", line 936, in list
    since=since)
  File "/usr/lib/python3.6/site-packages/docker/api/container.py", line 210, in containers
    res = self._result(self._get(u, params=params), True)
  File "/usr/lib/python3.6/site-packages/docker/api/client.py", line 267, in _result
    self._raise_for_status(response)
  File "/usr/lib/python3.6/site-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/lib/python3.6/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 400 Client Error: Bad Request ("client is newer than server (client API version: 1.35, server API version: 1.24)")
```

**Comment by circa10a** [comment]
@cesalo if `DOCKER_API_VERSION` does indeed solve this with the docker py library, try started ouroboros like this

```
docker run --name ouroboros -e DOCKER_API_VERSION=<value> pyouroboros/ouroboros
```

**Comment by cesalo** [comment]
Thanks @circa10a, unfortunately it didn't work. I had to upgrade docker.
