### ISSUE TITLE
Ouroboros copies entrypoint from old container

### ISSUE THREAD

**Issue by ginkel** [pyouroboros/ouroboros#337]
Hi there,

ouroboros seems to copy the entrypoint from the old Docker container when updating a container, which causes trouble if the entrypoint has changed between old and new image. This just happened for the `traefik` image (old entrypoint: `/traefik`, new entrypoint `/entrypoint.sh`), effectively bringing down all of our web-based infrastructure:

```
2019-09-14 06:40:31 : INFO : ouroboros : Version: 1.4.1-master
2019-09-14 06:40:31 : DEBUG : ouroboros : Ouroboros configuration: {'interval': 300, 'docker_sockets': ['unix://var/run/docker.sock'], 'log_level': 'debug', 'prometheus_addr': '0.0.0.0', 'prometheus_port': 8080, 'cleanup': True, 'influx_url': None, 'influx_port': None, 'influx_username': None, 'influx_password': None, 'data_export': 'prometheus', 'self_update': False, 'label_enable': True, 'hostname': 'a7c22635384c', 'docker_tls_verify': True}
[...]
2019-09-17 00:11:06 : INFO : dockerclient : traefik will be updated
2019-09-17 00:11:06 : DEBUG : dockerclient : Stopping container: traefik
2019-09-17 00:11:11 : DEBUG : connectionpool : http://localhost:None "POST /v1.35/containers/825b5a4a05f84be90d906291c2aba86d060c22724d5d0015417d346bb093e0b6/stop HTTP/1.1" 204 0
2019-09-17 00:11:11 : DEBUG : dockerclient : Removing container: traefik
2019-09-17 00:11:11 : DEBUG : connectionpool : http://localhost:None "DELETE /v1.35/containers/825b5a4a05f84be90d906291c2aba86d060c22724d5d0015417d346bb093e0b6?v=False&link=False&force=False HTTP/1.1" 204 0
2019-09-17 00:11:12 : DEBUG : connectionpool : http://localhost:None "POST /v1.35/containers/create?name=traefik HTTP/1.1" 201 88
2019-09-17 00:11:12 : DEBUG : connectionpool : http://localhost:None "GET /v1.35/containers/1d97831c32f58248f756290612dd0ca41966657c69859b0e355a719bd328c2b4/json HTTP/1.1" 200 None
2019-09-17 00:11:12 : DEBUG : connectionpool : http://localhost:None "GET /v1.35/networks/4ec99c5f8e144cb4dcf67b6628678082ec50e603d5051f0f12b6363c683d8081 HTTP/1.1" 200 None
2019-09-17 00:11:12 : DEBUG : connectionpool : http://localhost:None "POST /v1.35/networks/4ec99c5f8e144cb4dcf67b6628678082ec50e603d5051f0f12b6363c683d8081/disconnect HTTP/1.1" 200 0
2019-09-17 00:11:13 : DEBUG : connectionpool : http://localhost:None "POST /v1.35/networks/4ec99c5f8e144cb4dcf67b6628678082ec50e603d5051f0f12b6363c683d8081/connect HTTP/1.1" 200 0
2019-09-17 00:11:13 : DEBUG : connectionpool : http://localhost:None "GET /v1.35/networks/d3f9b5fde9ad8eb2d6808d628089c1e83e251bbd8410093de45cda2512d50eaf HTTP/1.1" 200 None
2019-09-17 00:11:13 : DEBUG : connectionpool : http://localhost:None "POST /v1.35/networks/d3f9b5fde9ad8eb2d6808d628089c1e83e251bbd8410093de45cda2512d50eaf/disconnect HTTP/1.1" 500 125
2019-09-17 00:11:13 : DEBUG : connectionpool : http://localhost:None "POST /v1.35/networks/d3f9b5fde9ad8eb2d6808d628089c1e83e251bbd8410093de45cda2512d50eaf/connect HTTP/1.1" 200 0
2019-09-17 00:11:16 : DEBUG : connectionpool : http://localhost:None "POST /v1.35/containers/1d97831c32f58248f756290612dd0ca41966657c69859b0e355a719bd328c2b4/start HTTP/1.1" 400 177
2019-09-17 00:11:16 : ERROR : base : Job "Interval container update for unix://var/run/docker.sock (trigger: interval[0:05:00], next run at: 2019-09-17 00:15:31 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.35/containers/1d97831c32f58248f756290612dd0ca41966657c69859b0e355a719bd328c2b4/start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 326, in update
    self.recreate(container, latest_image)
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 173, in recreate
    new_container.start()
  File "/usr/local/lib/python3.7/site-packages/docker/models/containers.py", line 400, in start
    return self.client.api.start(self.id, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/docker/api/container.py", line 1093, in start
    self._raise_for_status(res)
  File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python3.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 400 Client Error: Bad Request ("OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/traefik\": stat /traefik: no such file or directory": unknown")
```

**Comment by nick-solly** [comment]
I have a similar issue where changes to environment variables (coming from `ENV` instructions in the Dockerfile) are not reflected when Ouroboros updates the container.

**Comment by mazhead** [comment]
Same here when upgrading homeassistant:
https://github.com/home-assistant/docker/issues/107

Should be a option to only override if it was specified manually, e.g. during upgrade inspect image and compare with running?
