### ISSUE TITLE
Installing ouroboros on Pi4 Raspbian and I only get "ERROR : dockerclient : XXX has no tags.. you should clean it up! Ignoring."

### ISSUE THREAD

**Issue by andsoitgoes** [pyouroboros/ouroboros#338]
Hi everyone.

I'm running Docker version 19.03.1, build 74b1e89

I was able to use Ouroboros before and I'm not sure what's happened, now can I remember if I was running it on my Pi 4? Nope! But I'm pretty sure I was!

I'd appreciate any help, and if you need any other info I'm happy to provide that as well, I'm just a bit simple and might need some guidance as to what I need to provide you, currently that's all that's showing up in the logs so I'm also a bit lost.

Thanks in advance!

Quick update - Thought things were going better, but this is my current output - I'm having a hard time identifying what's going wrong. I will say that it seems to have updated the few things that were the most important, but as well I would very much like to fix the error logs. I can't seem to find the container images that it's mad at me for not having tags on.

```2019-09-22 23:26:54 : INFO : dockerclient : sonarr-preview will be updated

2019-09-22 23:27:02 : INFO : dockerclient : hassio_supervisor will be updated

2019-09-22 23:27:08 : INFO : dockerclient : radarr-preview will be updated

2019-09-22 23:27:18 : INFO : dockerclient : hassio_supervisor will be updated

2019-09-22 23:27:18 : ERROR : base : Job "Interval container update for unix://var/run/docker.sock (trigger: interval[0:05:00], next run at: 2019-09-22 23:31:20 UTC)" raised an exception

Traceback (most recent call last):

  File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 261, in _raise_for_status

    response.raise_for_status()

  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status

    raise HTTPError(http_error_msg, response=self)

requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.35/containers/be389acf5622bbf28d65653ec76feaa8aace6c5fb349b1cf153b7fe5dc38efcf/stop


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/local/lib/python3.7/site-packages/apscheduler/executors/base.py", line 125, in run_job

    retval = job.func(*job.args, **job.kwargs)

  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 326, in update

    self.recreate(container, latest_image)

  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 136, in recreate

    self.stop(container)

  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 123, in stop

    container.stop()

  File "/usr/local/lib/python3.7/site-packages/docker/models/containers.py", line 432, in stop

    return self.client.api.stop(self.id, **kwargs)

  File "/usr/local/lib/python3.7/site-packages/docker/utils/decorators.py", line 19, in wrapped

    return f(self, resource_id, *args, **kwargs)

  File "/usr/local/lib/python3.7/site-packages/docker/api/container.py", line 1152, in stop

    self._raise_for_status(res)

  File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 263, in _raise_for_status

    raise create_api_error_from_http_exception(e)

  File "/usr/local/lib/python3.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception

    raise cls(e, response=response, explanation=explanation)

docker.errors.NotFound: 404 Client Error: Not Found ("No such container: be389acf5622bbf28d65653ec76feaa8aace6c5fb349b1cf153b7fe5dc38efcf")
```

**Comment by DirtyCajunRice** [comment]
This is a common problem of resources with RPis. When this is happening what does the load/usage of your pi look like

**Comment by andsoitgoes** [comment]
> This is a common problem of resources with RPis. When this is happening what does the load/usage of your pi look like

Tasks: 251 total,   2 running, 248 sleeping,   0 stopped,   1 zombie%Cpu(s): 30.6 us,  5.4 sy,  0.0 ni, 61.2 id,  1.3 wa,  0.0 hi,  1.4 si,  0.0 st
MiB Mem :   3727.6 total,    354.0 free,    853.6 used,   2520.0 buff/cacheMiB Swap:    100.0 total,     15.4 free,     84.6 used.   2657.6 avail Mem 

My Pi is pretty low usage, I am running a fair number of docker containers, but since I posted this multiple containers have been updated fine, that error just keeps popping back up and I can't identify what it's specifically detailing.

If there's any other info I can provide, please let me know - and thanks in advance!

**Comment by DirtyCajunRice** [comment]
The error of cleanup normally happens when the new image has been pulled, but either outside of ouro, or ouro failed to kill the old container in a timely manner and it got in an out of sync state.

**Comment by olskar** [comment]
I to have this error on an intel nuc

`2019-12-15 12:46:40 : INFO : ouroboros : Version: 1.4.3-master


2019-12-15 12:46:40 : ERROR : dockerclient : ef8ea0ed98009370ba6b57f441495a55c02758aef96b2ef3d804f37724166779 has no tags.. you should clean it up! Ignoring.


2019-12-15 12:46:40 : ERROR : dockerclient : ef8ea0ed98009370ba6b57f441495a55c02758aef96b2ef3d804f37724166779 has no tags.. you should clean it up! Ignoring.`

How do you mean @DirtyCajunRice  ? Can I get rid of this error somehow?

**Comment by olskar** [comment]
I dont think resources is an issue on the nuc

**Comment by DirtyCajunRice** [comment]
no tags means no tags. not an ouro issue you have untagged containers

**Comment by manu-p** [comment]
Hi, maybe a clue?
Not an untagged **container** but an untagged **image**...

This happened to me when an image had `<none>` for TAG instead (for instance) of `latest`.
