### ISSUE TITLE
ouroboros troubles in autostarting services

### ISSUE THREAD

**Issue by sm0kingm4n** [pyouroboros/ouroboros#340]
hi all,

I have all my services in a single docker compose file. I use ouroboros to auto-update all my containers.

_**Every time a container it's updated it won't autostart automatically, the relevant service it's down (404 error) and I need to manually restart it.**_

There's a way to set everything automated by ouroboros setup in the docker-compose file and/or some cron/terminal bash script for the purpose?
my system it's an home nas debian buster x64 machine with 16gb ram (approx 4 gb used on full load).

relevant **ouroboros section of my docker-compose.yml**
```
###
ouroboros:
container_name: ouroboros
hostname: ouroboros
image: pyouroboros/ouroboros:latest
environment:
- CLEANUP=true
- INTERVAL=3600
- LOG_LEVEL=info
- SELF_UPDATE=true
- IGNORE=mongo influxdb postgres mariadb
- PUID=${PUID}
- PGID=${PGID}
- TZ=${TZ}
network_mode: host
labels:
- "traefik.enable=false"
restart: unless-stopped
volumes:
- /var/run/docker.sock:/var/run/docker.sock
###
```
output of "**docker logs ouroboros**" :
```
*2019-10-07 14:19:02 : INFO : ouroboros : Version: 1.4.2-master
2019-10-07 15:00:57 : INFO : dockerclient : ums will be updated
2019-10-07 15:13:39 : INFO : dockerclient : netdata will be updated
2019-10-07 16:33:42 : INFO : dockerclient : calibreweb will be updated
2019-10-08 00:20:09 : ERROR : dockerclient : Issue detecting openvpn-server's image tag. Skipping...
2019-10-08 00:33:38 : INFO : dockerclient : jackett will be updated
2019-10-08 00:33:46 : ERROR : base : Job "Interval container update for unix://var/run/docker.sock (trigger: interval[0:13:20], next run at: 2019-10-08 00:45:42 CEST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 326, in update
    self.recreate(container, latest_image)
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 162, in recreate
    network.connect(**new_network_config)
  File "/usr/local/lib/python3.7/site-packages/docker/models/networks.py", line 57, in connect
    container, self.id, *args, **kwargs
  File "/usr/local/lib/python3.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/docker/api/network.py", line 242, in connect_container_to_network
    ipv6_address=ipv6_address, link_local_ips=link_local_ips
  File "/usr/local/lib/python3.7/site-packages/docker/api/container.py", line 650, in create_endpoint_config
    return EndpointConfig(self._version, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/docker/types/networks.py", line 17, in __init__
    self["Links"] = normalize_links(links)
  File "/usr/local/lib/python3.7/site-packages/docker/utils/utils.py", line 445, in normalize_links
    return ['{0}:{1}'.format(k, v) if v else k for k, v in sorted(links)]
  File "/usr/local/lib/python3.7/site-packages/docker/utils/utils.py", line 445, in <listcomp>
    return ['{0}:{1}'.format(k, v) if v else k for k, v in sorted(links)]
ValueError: too many values to unpack (expected 2)
2019-10-08 02:06:08 : ERROR : dockerclient : Issue detecting beets's image tag. Skipping...
2019-10-08 02:20:10 : ERROR : dockerclient : Issue detecting dnscrypt's image tag. Skipping...*
```

**Comment by DirtyCajunRice** [comment]
Need openvpn docker config

**Comment by sm0kingm4n** [comment]
here's my **openvpn section in my docker-compose**:
```
########## OPENVPN
  openvpn:
    container_name: openvpn-server
    image: kylemanna/openvpn:latest
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "5"
    restart: always
    hostname: openvpn
    volumes:
      - ${USERDIR}/docker/openvpn/config:/etc/openvpn
    ports:
      - "1082:1194/udp"
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      pihole_net:
        ipv4_address: 172.2.1.2
```

**Comment by DirtyCajunRice** [comment]
@sm0kingm4n  If I recall correctly, its because you have designated a specific ip and ouro creates the new container before shutting down the old one. If the ip is already bound to another container it cant be bound to the “new” container. @circa10a fact check me?

**Comment by itsthejb** [comment]
@DirtyCajunRice thanks for the input on this; it might explain a similar issue I'm seeing. I assume starting the new one before is a feature to improve availability? It might be nice to have the option to reverse this to avoid this problem
