### ISSUE TITLE
ValueError: Invalid IPv6 URL

### ISSUE THREAD

**Issue by CptDayDreamer** [pyouroboros/ouroboros#368]
I'm running ouroboros in a docker-compose file and yesterday it worked but now I got the error in the logs of the container:

```
2020-02-12 18:24:17 : INFO : ouroboros : Version: 1.4.3-master
Traceback (most recent call last):
  File "/usr/local/bin/ouroboros", line 5, in <module>
    main()
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/ouroboros.py", line 151, in main
    notification_manager = NotificationManager(config, data_manager)
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/notifiers.py", line 13, in __init__
    self.apprise = self.build_apprise()
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/notifiers.py", line 29, in build_apprise
    add = apprise_obj.add(notifier)
  File "/usr/local/lib/python3.7/site-packages/apprise/Apprise.py", line 227, in add
    instance = Apprise.instantiate(_server, asset=asset, tag=tag)
  File "/usr/local/lib/python3.7/site-packages/apprise/Apprise.py", line 112, in instantiate
    results = plugins.url_to_dict(url)
  File "/usr/local/lib/python3.7/site-packages/apprise/plugins/__init__.py", line 461, in url_to_dict
    results = SCHEMA_MAP[schema].parse_url(_url)
  File "/usr/local/lib/python3.7/site-packages/apprise/plugins/NotifyEmail.py", line 733, in parse_url
    results = NotifyBase.parse_url(url)
  File "/usr/local/lib/python3.7/site-packages/apprise/plugins/NotifyBase.py", line 390, in parse_url
    results = URLBase.parse_url(url, verify_host=verify_host)
  File "/usr/local/lib/python3.7/site-packages/apprise/URLBase.py", line 490, in parse_url
    url, default_schema='unknown', verify_host=verify_host)
  File "/usr/local/lib/python3.7/site-packages/apprise/utils.py", line 340, in parse_url
    parsed = urlparse('http://%s' % host)
  File "/usr/local/lib/python3.7/urllib/parse.py", line 368, in urlparse
    splitresult = urlsplit(url, scheme, allow_fragments)
  File "/usr/local/lib/python3.7/urllib/parse.py", line 417, in urlsplit
    raise ValueError("Invalid IPv6 URL")

ValueError: Invalid IPv6 URL
```

I don't know what happend. The only thing I did was increase the interval to a very high value.

The docker-compose without all other container:

```
version: "3"
services:
  ouroboros:
    container_name: ouroboros
    hostname: ouroboros
    image: pyouroboros/ouroboros
    environment:
      - CLEANUP=true
      - INTERVAL=300
      - LATEST=true
      - LOG_LEVEL=info
      - SELF_UPDATE=true
      - IGNORE=nginx
      - TZ=Europe/Berlin
      - NOTIFIERS=mailto://<username>:<password>@gmail.com discord://.......
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

**Comment by caronc** [comment]
Apprise makes use of the libraries that ship with Python to parse a URL string. You're `mailto://` has some strange characters in it that even Python's underlining library can't parse. 

By chance does your password or username contain an excessive amount of colons (`:`) causing it to confuse your password for an IPV6 hostname? e.g: `mailto://user:ab:abc:abde:a423:ajk@gmail.com`

Check out this [section of the troubleshooting](https://github.com/caronc/apprise/wiki/Troubleshooting#special-characters-and-url-conflicts) which shows you how you can escape special characters. Colons can become **%3A** (_but don't escape the colon between your user and your password_).  For example, in the above `mailto://` url would have worked as this instead (_escaped colons_): `mailto://user:ab%3Aabc%3Aabde%3Aa423%3Aajk@gmail.com`.

Alternatively, contact me at lead2gold@gmail.com with your `mailto://` URL (just change a few letters only for your own safety).  I have never seen that error before that you're getting, I would need to reproduce the error to figure out how i can add bulletproofing to it if you feel it's necessary.

**Comment by CptDayDreamer** [comment]
@caronc was right. My password contains the two symbols 
After having a look on the page https://krypted.com/utilities/html-encoding-reference/ I could figure out the right escape characters for my purpose. For me it were:
%21 : !
%5B : [
